Repository infor-design/enterprise, pull requests merged in 2018-06, with the labels that each got.

#161 SOHO-7580 - Merge Searchfield and ToolbarSearchfield APIs
  app/data/searchfield-shopping-categories.json
  app/views/components/searchfield/example-categories-and-go-button.html
  app/views/components/searchfield/example-categories-full.html
  app/views/components/searchfield/example-different-template.html
  app/views/components/searchfield/example-go-button.html
  app/views/components/searchfield/example-index.html
  app/views/components/toolbar-flex/example-searchfield.html
  app/views/components/toolbarsearchfield/example-collapsible-on-mobile.html
  app/views/components/toolbarsearchfield/test-invoke-with-contents.html
  scripts/controls.js
  src/components/autocomplete/autocomplete.jquery.js
  src/components/autocomplete/autocomplete.js
  src/components/button/_button.scss
  src/components/components.jquery.js
  src/components/components.js
  src/components/datagrid/datagrid.js
  src/components/icons/_icons.scss
  src/components/lookup/lookup.js
  src/components/popupmenu/popupmenu.js
  src/components/searchfield/_searchfield-toolbar.scss
  src/components/searchfield/_searchfield.scss
  src/components/searchfield/searchfield.jquery.js
  src/components/searchfield/searchfield.js
  src/components/searchfield/toolbarsearchfield.jquery.js
  src/components/toolbar-flex/toolbar-flex.js
  src/components/toolbar/toolbar.js
  src/components/toolbarsearchfield/toolbarsearchfield.jquery.js
  src/components/typography/_typography.scss
  src/core/_controls.scss
  src/utils/environment.js
  src/utils/renderloop.js
  src/utils/utils.js
  test/components/searchfield/searchfield-api.func-spec.js
  test/components/searchfield/searchfield-categories.func-spec.js
  test/components/searchfield/searchfield.e2e-spec.js
  test/components/searchfield/searchfield.func-spec.js
Labels: type: enhancement, type: maintanence

#290 Q/A - Searchfield: Fixed missing `selected` event trigger on input elements
  src/components/searchfield/searchfield.js
  test/components/searchfield/searchfield-events.func-spec.js
Labels: type: bug

#302 Q/A - 268 - Undefined Dropdown Icons throwing an error
  app/views/components/dropdown/example-readonly.html
  src/components/dropdown/dropdown.js
Labels: status: critical

#304 Added a fix to ensure modal submit is enabled when editors or on the …
  app/views/components/modal/test-validation-editor.html
  src/components/validation/validator.js
  test/components/modal/modal.e2e-spec.js
Labels: status: critical
