Repository infor-design/enterprise, pull requests merged in 2018-07, with the labels that each got.

#289 Added release notes for 4.8.0
  docs/CHANGELOG.md
Labels: status: critical

#325 #315 Validation Bug Fix / Fix Broken Tests
  app/views/components/input/example-index.html
  app/views/components/modal/example-validation.html
  app/views/components/validation/test-email-validation.html
  src/components/icons/_icons.scss
  src/components/validation/validation.js
  src/components/validation/validation.utils.js
  src/components/validation/validator.js
  test/components/button/button.e2e-spec.js
  test/components/validation/validation.e2e-spec.js
Labels: status: critical

#368 240 - Fix Grid Freezes when Copied a 1000 rows
  src/utils/excel.js
Labels: type: enhancement

#467 466 - Tab key no longer causes Dropdown lists to open
  src/components/dropdown/dropdown.js
  test/components/dropdown/dropdown.e2e-spec.js
Labels: type: bug

#487 Fix for backspace percentage
  src/components/mask/mask-input.js
Labels: type: bug

#486 344 - Lookup API and E2E Tests
  test/components/lookup/lookup-api.func-spec.js
  test/components/lookup/lookup.e2e-spec.js
  test/components/toast/toast-api.func-spec.js
  test/components/toast/toast.e2e-spec.js
Labels: type: maintanence

#497 Hotfix for npm audit feedback, nightlies & update test dependencies
  .travis.yml
  package-lock.json
  package.json
  scripts/configs/sass.js
  test/components/datepicker/datepicker.e2e-spec.js
  test/protractor.local.bs.conf.js
Labels: type: regression bug

#504 245 - add longpress behavior
  app/app.js
  app/views/behaviors/longpress/example-index.html
  app/views/behaviors/longpress/test-e2e-overlay-toggle.html
  src/behaviors/longpress/longpress.js
  src/behaviors/longpress/longpress.scss
  src/core/_controls.scss
  src/index.js
  src/utils/environment.js
  test/behaviors/longpress/longpress-events.func-spec.js
  test/behaviors/longpress/longpress.e2e-spec.js
  test/karma.conf.js
  test/protractor.ci.bs.conf.js
  test/protractor.ci.conf.js
  test/protractor.local.bs.conf.js
  test/protractor.local.debug.conf.js
Labels: type: enhancement

#494 NG-136 - Add a type check to fix broken NG tests
  src/components/dropdown/dropdown.js
Labels: type: regression bug

#479 Added fix for #478 and a test
  src/components/editor/editor.js
  src/components/trackdirty/trackdirty.js
  test/components/editor/editor.e2e-spec.js
Labels: type: regression bug

#476 474 - Escape key causing the Dropdown to re-open it's list unexpectedly
  src/components/dropdown/dropdown.js
  test/components/dropdown/dropdown.e2e-spec.js
Labels: type: regression bug

#503 315 additional validation case
  app/views/components/contextualactionpanel/example-workspaces.html
  app/views/components/datagrid/test-contextualactionpanel.html
  app/views/components/datepicker/example-month-year-format.html
  app/views/components/fileupload/example-index.html
  app/views/components/radios/example-index.html
  app/views/components/radios/test-validation.html
  app/views/components/tooltip/test-positions.html
  app/views/components/validation/example-index.html
  app/views/components/validation/example-multiple-errors.html
  app/views/components/validation/example-short-fields.html
  app/views/components/validation/example-validation-form.html
  app/views/components/validation/test-all-field-types.html
  app/views/components/validation/test-events.html
  app/views/components/validation/test-legacy-tooltip.html
  docs/TEAMS.md
  docs/TESTING.md
  src/components/colorpicker/_colorpicker.scss
  src/components/dropdown/_dropdown.scss
  src/components/fileupload/fileupload.js
  src/components/modal/modal.js
  src/components/searchfield/searchfield.js
  src/components/spinbox/_spinbox.scss
  src/components/timepicker/timepicker.js
  src/components/validation/validation.jquery.js
  src/components/validation/validation.js
  src/components/validation/validator.js
  test/baseline/radio-init-chrome-1200x800-dpr-1.png
  test/components/multiselect/multiselect.e2e-spec.js
  test/components/radios/radios.e2e-spec.js
  test/components/timepicker/timepicker-settings.func-spec.js
  test/components/validation/validation-api.func-spec.js
  test/components/validation/validation.e2e-spec.js
Labels: type: regression bug

#527 Added null check to updateDataset
  src/components/datagrid/datagrid.js
  test/components/datagrid/datagrid-api.func-spec.js
Labels: type: regression bug

#532 Fixes #529 Added eventing fix and fixed an error
  app/server.js
  app/src/js/middleware/option-handler.js
  package.json
  src/components/autocomplete/autocomplete.js
  src/components/listview/listview.js
  src/components/popupmenu/popupmenu.js
  test/components/autocomplete/autocomplete.e2e-spec.js
  test/components/datepicker/datepicker.e2e-spec.js
  test/helpers/e2e-utils.js
  test/kitchen-sink.e2e-spec.js
Labels: type: regression bug

#533 519 - Fix for prematurely closing application menus
  src/components/accordion/accordion.js
Labels: type: regression bug
