Repository infor-design/enterprise, pull requests merged in 2018-08, with the labels that each got.

#549 507 - Fixed bad test page routing
  app/views/components/popupmenu/example-context-menu-behavior.html
Labels: type: maintanence

#679 548 - Fix paste and IE errors
  src/utils/environment.js
Labels: status: critical, type: regression bug

#704 548 - Added a fix to not strip ng from text
  src/components/editor/editor.js
  test/components/editor/editor-api.func-spec.js
Labels: type: regression bug

#705 Added fix for today button not working
  src/components/datepicker/datepicker.js
  test/components/datepicker/datepicker-api.func-spec.js
Labels: type: regression bug

#709 701 - submenu cutoff
  src/components/popupmenu/popupmenu.js
  test/components/datagrid/datagrid.e2e-spec.js
Labels: type: regression bug

#707 702 - Fix for App Menu Searchfield's clear button
  src/components/applicationmenu/applicationmenu.js
  src/components/autocomplete/autocomplete.js
  src/components/searchfield/searchfield.js
  test/components/autocomplete/autocomplete-api.func-spec.js
Labels: type: regression bug

#719 Added fix for not running source
  app/views/components/autocomplete/example-searchfield.html
  src/components/datagrid/datagrid.editors.js
  src/components/searchfield/searchfield.js
Labels: type: regression bug

#729 728 - Add fix for up key
  src/components/datepicker/datepicker.js
  test/components/calendar/calendar.e2e-spec.js
  test/components/datepicker/datepicker.e2e-spec.js
Labels: status: critical, type: regression bug
