Repository infor-design/enterprise, pull requests merged in 2019-05, with the labels that each got.

#2135 1978 - Expandable area updates within application menu (Readded)
  app/views/components/applicationmenu/example-personalized-role-switcher.html
  docs/CHANGELOG.md
  src/components/applicationmenu/applicationmenu.js
Labels: priority: high

#2210 2134 - Colorpicker text not visible in IE11
  docs/CHANGELOG.md
  src/components/colorpicker/_colorpicker.scss
Labels: status: on hold :pause_button:

#2202 2072 - Uplift datagrid fixes
  package.json
  src/components/datagrid/_datagrid-uplift.scss
  src/core/_controls-uplift.scss
  src/themes/theme-uplift-contrast.scss
  src/themes/theme-uplift-dark.scss
  src/themes/theme-uplift-light.scss
Labels: status: wip :construction:

#2187 2096 - RTL Radio button label spacing
  src/components/radios/_radios.scss
Labels: status: on hold :pause_button:

#2262 2258 - Allow manual personalization [v4.19.x]
  app/views/includes/head.html
  src/components/colorpicker/colorpicker.js
  src/components/personalize/personalize.bootstrap.js
  src/components/personalize/personalize.js
  src/components/personalize/readme.md
  test/components/personalize/personalize-api.func-spec.js
Labels: priority: critical
