Repository infor-design/enterprise, pull requests merged in 2022-05, with the labels that each got.

#6371 6369 - Fix related searchfield new design in toolbar and tabs module
  app/views/components/tabs-module/example-toolbar-with-spillover.html
  docs/CHANGELOG.md
  src/components/listview/_listview.scss
  src/components/searchfield/_searchfield-new.scss
  src/components/searchfield/_searchfield-toolbar.scss
  src/components/searchfield/_searchfield.scss
  src/components/tabs-module/_tabs-module.scss
  src/components/tabs/tabs.js
  src/components/toolbar-flex/_toolbar-flex-searchfield.scss
  src/components/toolbar/_toolbar-new.scss
  src/components/toolbar/_toolbar.scss
  src/core/_config.scss
  test/baseline/datagrid-alerts-xs-chrome-1200x800-dpr-1.png
  test/baseline/datagrid-compact-chrome-1200x800-dpr-1.png
  test/baseline/datagrid-compact-toggle-chrome-1200x800-dpr-1.png
  test/baseline/datagrid-filter-alt-row-shading-chrome-1200x800-dpr-1.png
  test/baseline/datagrid-modal-size-two-chrome-1200x800-dpr-1.png
  test/baseline/datagrid-paging-indeterminate-single-first-page-chrome-1200x800-dpr-1.png
  test/baseline/datagrid-paging-indeterminate-single-last-page-chrome-1200x800-dpr-1.png
  test/baseline/datagrid-summary-row-paging-chrome-1200x800-dpr-1.png
  test/baseline/datagrid-tags-badges-chrome-1200x800-dpr-1.png
  test/baseline/header-index-chrome-1200x800-dpr-1.png
  test/baseline/lookup-index-chrome-1200x800-dpr-1.png
  test/baseline/lookup-min-width-chrome-1200x800-dpr-1.png
  test/baseline/searchfield-clear2-chrome-1200x800-dpr-1.png
  test/baseline/searchfield-collapse-size-chrome-1200x800-dpr-1.png
  test/baseline/searchfield-init-chrome-1200x800-dpr-1.png
  test/baseline/searchfield-open-chrome-1200x800-dpr-1.png
  test/baseline/toolbar-flex-searchfield-collapsible-chrome-766x700-dpr-1.png
  test/baseline/toolbar-flex-searchfield-non-collapsible-chrome-766x700-dpr-1.png
  test/baseline/toolbar-searchfield-alignment-chrome-1200x800-dpr-1.png
  test/baseline/toolbar-searchfield-init-chrome-1200x800-dpr-1.png
  test/baseline/toolbar-searchfield-init-chrome-766x600-dpr-1.png
Labels: priority: high

#6443 6120 - Fix addMenuElementLinks incorrectly executed when having multi-level submenus
  docs/CHANGELOG.md
  src/components/toolbar-flex/toolbar-flex.item.js
Labels: type: patch

#6461 6446 - Fix token issue and minor deps
  docs/CHANGELOG.md
  package.json
  test/baseline-images/personalize-dark-theme-default-color-snap.png
  test/baseline-images/week-specific-week-snap.png
  test/components/badges/badges.puppeteer-spec.js
  test/components/personalize/personalize.puppeteer-spec.js
  test/components/week-view/week-view.puppeteer-spec.js
Labels: type: patch, priority: high
