Repository infor-design/enterprise, pull requests merged in 2023-04, with the labels that each got.

#7417 5061. Fix on popupmenu arrow not appearing when showArrow is true
  app/views/components/popupmenu/example-icons.html
  app/views/components/popupmenu/example-show-arrow.html
  docs/CHANGELOG.md
  src/components/popupmenu/popupmenu.js
Labels: needs qa

#7425 7207 - builder subtitle text not visible
  docs/CHANGELOG.md
  src/components/page-patterns/_builder.scss
Labels: needs qa

#7418 7240 - datepicker validation update update
  app/views/components/datepicker/test-mask-after-update.html
  docs/CHANGELOG.md
  src/components/datepicker/datepicker.js
Labels: needs qa

#7415 7377/7360 - Add CSS utility classes and fix centering of contents in emptymessage
  app/src/docs.scss
  app/src/index.scss
  app/views/components/button/example-button-with-hitbox.html
  app/views/components/css-utilities/example-index.html
  app/views/components/emptymessage/test-centered-content.html
  docs/CHANGELOG.md
  scripts/data/expected-files.json
  src/components/cards/_cards.scss
  src/components/utilities/readme.md
  src/core/_css-utilities.scss
  src/themes/theme-classic-contrast.scss
  src/themes/theme-classic-dark.scss
  src/themes/theme-classic-light.scss
  src/themes/theme-new-contrast.scss
  src/themes/theme-new-dark.scss
  src/themes/theme-new-light.scss
Labels: needs qa

#7357 7234 - Updated example page and styles
  app/views/components/counts/example-header.html
  app/views/components/counts/example-hero.html
  app/views/components/counts/test-widget-long-title.html
  app/views/components/datagrid/test-selected-event.html
  docs/CHANGELOG.md
  src/components/counts/_counts.scss
  src/components/homepage/_homepage.scss
  src/components/personalize/personalize.styles.js
Labels: needs qa

#7416 7302 - Colors should remain the same when changing theme colors
  docs/CHANGELOG.md
  src/components/accordion/_accordion.scss
  src/components/applicationmenu/_applicationmenu-new.scss
  src/components/personalize/personalize.styles.js
  src/components/personalize/readme.md
  src/themes/theme-classic-contrast.scss
  src/themes/theme-classic-dark.scss
  src/themes/theme-classic-light.scss
  src/themes/theme-new-contrast.scss
  src/themes/theme-new-dark.scss
  src/themes/theme-new-light.scss
Labels: needs qa

#7447 7382 - Clear icon adjustment
  src/components/searchfield/_searchfield.scss
Labels: needs qa, passed qa

#7426 7209 - header components alignment
  docs/CHANGELOG.md
  src/components/header/_header.scss
Labels: needs qa

#7422 7406 - Button Adjust personalized colors
  docs/CHANGELOG.md
  src/components/button/_button-new.scss
  src/components/button/_button.scss
  src/components/header/_header.scss
  src/components/personalize/personalize.js
  src/components/personalize/personalize.styles.js
  src/core/_config.scss
  src/themes/theme-new-contrast.scss
  src/themes/theme-new-dark.scss
  src/themes/theme-new-light.scss
Labels: status: wip :construction:, needs qa

#7429 7390 - Searchfield fix collapsible icon color and behavior
  app/views/components/header/example-breadcrumbs.html
  app/views/components/header/example-flex-toolbar.html
  docs/CHANGELOG.md
  src/components/breadcrumb/_breadcrumb.scss
  src/components/header/_header-new.scss
  src/components/header/_header.scss
  src/components/masthead/_masthead-new.scss
  src/components/personalize/personalize.styles.js
  src/components/searchfield/_searchfield-toolbar-new.scss
  src/components/searchfield/_searchfield-toolbar.scss
  src/components/searchfield/_searchfield.scss
  src/components/searchfield/searchfield.js
  src/components/toolbar-flex/_toolbar-flex-searchfield-new.scss
  src/components/toolbar-flex/_toolbar-flex-searchfield.scss
  src/components/toolbar-flex/_toolbar-flex.scss
  src/components/toolbar/_toolbar-new.scss
  src/core/_config.scss
  src/themes/theme-classic-contrast.scss
  src/themes/theme-classic-dark.scss
  src/themes/theme-new-dark.scss
Labels: needs qa, passed qa

#7460 7459 - Added hover style for contextual toolbar
  docs/CHANGELOG.md
  src/components/toolbar/_toolbar-new.scss
Labels: needs qa

#7458 7234 - Style change
  src/components/personalize/personalize.styles.js
Labels: needs qa

#7448 7383 - Popupmenu button isn't visible
  src/components/contextualactionpanel/_contextualactionpanel.scss
  src/components/toolbar/toolbar.js
Labels: needs qa
