Repository infor-design/enterprise, pull requests merged in 2023-09, with the labels that each got.

#7878 7680 - Added expanded default for expandable formatter
  app/views/components/datagrid/example-expandable-row.html
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.formatters.js
  src/components/datagrid/datagrid.js
Labels: needs qa

#7886 7479 - Header Flex
  app/views/components/header/example-long-title-with-button.html
  app/views/components/header/example-searchfield-large.html
  docs/CHANGELOG.md
Labels: needs qa

#7882 7881 - Add more tab fixes
  src/components/datagrid/readme.md
  src/components/monthview/monthview.js
  src/components/personalize/personalize.js
  src/components/tabs-module/_tabs-module.scss
  src/themes/theme-classic-dark.scss
Labels: needs qa

#7885 7590 - Refix issues in editor
  docs/CHANGELOG.md
  src/components/editor/editor.js
  src/utils/xss.js
Labels: needs qa

#7904 7772 - Tabs focus border RTL
  docs/CHANGELOG.md
  src/components/tabs/tabs.js
Labels: needs qa

#7907 7801 - Updated hover color for breadcrumb in header
  docs/CHANGELOG.md
  src/components/header/_header.scss
  src/components/personalize/personalize.styles.js
  src/themes/theme-new-dark.scss
Labels: needs qa

#7888 7850 - Fix on focus border being off in chart legend items
  docs/CHANGELOG.md
  src/components/charts/_charts.scss
  src/components/pie/pie.js
Labels: needs qa

#7912 7905 - Fix lookup text positioning
  docs/CHANGELOG.md
  src/components/lookup/_lookup.scss
Labels: type: patch, needs qa

#7920 7889 - Fix chart title's width for column charts
  app/views/components/column-grouped/example-axis-labels.html
  app/views/components/column/example-rotate.html
  docs/CHANGELOG.md
  src/components/cards/_cards.scss
Labels: needs qa

#7913 7908 - Add new disabled filter styles
  docs/CHANGELOG.md
  src/components/datagrid/_datagrid.scss
  src/core/_config.scss
  src/themes/theme-classic-contrast.scss
  src/themes/theme-classic-dark.scss
  src/themes/theme-new-contrast.scss
  src/themes/theme-new-dark.scss
  src/themes/theme-new-light.scss
Labels: type: patch, needs qa

#7929 7631 - Fix XSS when setting up tree node
  app/views/components/tree/test-add-node.html
  docs/CHANGELOG.md
  src/components/tree/tree.jquery.js
Labels: needs qa

#7902 7896 - Fix widget sizes
  app/views/components/cards/example-expandable.html
  app/views/components/cards/test-datagrid.html
  app/views/components/cards/test-full-width.html
  app/views/components/cards/test-paging-datagrid.html
  app/views/components/cards/test-tabs-card.html
  app/views/components/homepage/example-add-widget.html
  app/views/components/homepage/example-filled.html
  app/views/components/homepage/example-monthviews.html
  app/views/components/homepage/example-scenario-h.html
  docs/CHANGELOG.md
  src/components/calendar/_calendar-toolbar.scss
  src/components/cards/_cards-new.scss
  src/components/cards/_cards.scss
  src/components/homepage/_homepage.scss
  src/components/homepage/homepage.js
Labels: needs qa, needs design review

#7918 7793 - Editor Text Header and Color
  docs/CHANGELOG.md
  src/components/editor/editor.js
Labels: needs design review

#7930 7678 - popover content scrollable
  app/views/components/popover/test-popover-scrollable.html
  docs/CHANGELOG.md
  src/components/tooltip/_tooltip.scss
Labels: needs qa

#7945 7944/7943 - Fix hover colors
  docs/CHANGELOG.md
  src/components/contextualactionpanel/_contextualactionpanel.scss
  src/components/personalize/personalize.styles.js
Labels: needs qa

#7940 7938 - Add fix to color and remove class on heros
  app/views/components/homepage/example-hero-widget.html
  docs/CHANGELOG.md
  src/components/homepage/_homepage.scss
Labels: needs qa

#7948 7941 - Fix Column chart error
  docs/CHANGELOG.md
  src/components/charts/charts.js
  src/components/column/column.js
  src/components/personalize/personalize.styles.js
  src/components/slider/_slider.scss
  test/components/personalize/personalize-api-func-test.js
Labels: priority: high, needs qa

#7952 7897 - Fix standalone toolbar dropdown label visibility for dark mode
  docs/CHANGELOG.md
  src/components/toolbar/_toolbar.scss
  src/core/_config.scss
  src/themes/theme-classic-dark.scss
  src/themes/theme-new-dark.scss
Labels: needs qa

#7931 7899 - Adjusted radio button dot centering
  docs/CHANGELOG.md
  src/components/radios/_radios-new.scss
  src/components/radios/_radios.scss
Labels: needs qa

#7953 1531 - Placeholder Datagrid
  app/views/components/datagrid/example-placeholder.html
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.formatters.js
Labels: needs qa

#7946 7796 - editor header firefox change
  docs/CHANGELOG.md
  src/components/editor/_editor.scss
  src/components/editor/editor.js
Labels: needs qa

#7950 7910 - Fix on go button misalignment
  docs/CHANGELOG.md
  src/components/searchfield/_searchfield-toolbar.scss
  src/components/toolbar-flex/_toolbar-flex.scss
Labels: needs qa

#7961 1541 - dropdown maxwidth expand
  app/views/components/dropdown/example-dropdown-wide-width.html
  docs/CHANGELOG.md
  src/components/dropdown/dropdown.js
Labels: needs qa

#7964 7807 - Added undefined check for column settings to avoid errors in spacer
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.js
Labels: needs qa

#7965 7926 - Adjusted positioning of text inside Weekview footer cell.
  docs/CHANGELOG.md
  src/components/datepicker/_datepicker.scss
  src/components/week-view/_week-view.scss
Labels: needs qa

#7971 7815 - Fix on dropdown not focusing in mobile
  docs/CHANGELOG.md
  src/components/dropdown/_dropdown.scss
  src/components/dropdown/dropdown.js
Labels: needs qa

#7936 7827 - Added overflow in modal body for horizontal scroll
  app/views/components/modal/test-overflow-horizontal.html
  docs/CHANGELOG.md
  src/components/modal/_modal.scss
  src/components/modal/modal.js
Labels: needs qa

#7895 7832 - Adjusted position and hover color for custom button
  app/views/components/searchfield/example-buttons.html
  docs/CHANGELOG.md
  src/components/searchfield/_searchfield-new.scss
  src/components/searchfield/_searchfield-toolbar.scss
  src/components/searchfield/_searchfield.scss
  src/components/searchfield/searchfield.js
  src/components/toolbar-flex/_toolbar-flex-searchfield.scss
  src/components/toolbar-flex/_toolbar-flex.scss
Labels: needs qa

#7969 7014 - Centered drilldown button within Datagrid cell.
  docs/CHANGELOG.md
  src/components/datagrid/_datagrid-new.scss
  src/components/datagrid/_datagrid.scss
Labels: needs qa

#7975 7806 - Added check on setting current date
  app/views/components/calendar/test-provided-date.html
  docs/CHANGELOG.md
  src/components/monthview/monthview.js
Labels: needs qa

#7960 518 - Fix icon pipeline
  app/package.json
  app/views/components/emptymessage/example-index.html
  app/views/components/icons/example-empty-widgets.html
  app/views/components/icons/example-pseudo-elements.html
  docs/CHANGELOG.md
  package-lock.json
  package.json
  scripts/build/create-svg-html.js
  src/components/icons/_icons-new.scss
  src/components/swipe-action/_swipe-action.scss
Labels: needs qa

#7985 7776 - line localize bottom spacing rtl
  docs/CHANGELOG.md
  src/components/cards/_cards-new.scss
Labels: needs qa

#7984 7915 - card is selected trigger tabs
  app/views/components/cards/test-tabs-card.html
  docs/CHANGELOG.md
  src/components/cards/cards.js
Labels: needs qa

#7986 7919 - Adjusted field filter focus borders
  docs/CHANGELOG.md
  src/components/button/_button.scss
  src/components/datepicker/_datepicker.scss
  src/components/monthview/_monthview.scss
Labels: needs qa

#7987 7813 - dropdown empty icons
  docs/CHANGELOG.md
  src/components/dropdown/dropdown.js
Labels: needs qa

#7983 7804 - Add mobile nav features and fixes
  app/views/components/module-nav/example-index.html
  docs/CHANGELOG.md
  src/components/cards/cards.js
  src/components/module-nav/module-nav.js
  src/components/module-nav/module-nav.scss
  src/components/module-nav/module-nav.switcher.scss
  src/core/_config.scss
  src/themes/theme-new-contrast.scss
  src/themes/theme-new-dark.scss
Labels: needs qa

#7980 7800 - Fix legend colors for selected days of week
  app/views/components/calendar/test-weekends-color.html
  app/views/components/calendar/test-weekends-disable.html
  docs/CHANGELOG.md
  src/components/monthview/_monthview.scss
  src/components/monthview/monthview.js
  src/components/week-view/week-view.js
Labels: needs qa

#7994 7991 - Fix Checkbox and Tab Darkmode colors
  app/views/components/cards/test-tabs-card.html
  docs/CHANGELOG.md
  src/core/_config.scss
  src/themes/theme-classic-dark.scss
  src/themes/theme-new-dark.scss
Labels: needs qa

#7968 7783 - button menu secondary combo
  app/views/components/button/example-menubutton.html
  docs/CHANGELOG.md
  src/components/button/_button-new.scss
  src/components/button/_button.scss
  src/components/personalize/personalize.js
  src/components/personalize/personalize.styles.js
  src/core/_config.scss
  src/themes/theme-new-dark.scss
Labels: needs qa

#7981 7979 - Fix bug with ui selected row
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.js
Labels: needs qa

#7989 7614 - Fix overlapping axis labels when bar text is lengthy
  app/views/components/bar/test-axis-labels-with-long-bar-texts.html
  docs/CHANGELOG.md
  src/components/bar/bar.js
  src/components/cards/_cards-new.scss
Labels: needs qa

#8004 7782 - Fix appmenu switcher button hover background color
  docs/CHANGELOG.md
  src/components/applicationmenu/_applicationmenu-new.scss
Labels: needs qa

#8003 518 - Change color of empty message
  src/components/emptymessage/_emptymessage-new.scss
  src/components/emptymessage/_emptymessage.scss
  src/core/_config.scss
  src/themes/theme-classic-dark.scss
Labels: needs qa

#7998 1546 - shared popupmenu placement
  app/views/components/popupmenu/test-context-menu-shared.html
  docs/CHANGELOG.md
  src/components/popupmenu/popupmenu.js
Labels: needs qa

#7990 7739 - Added options for alternate formatting in weekview
  app/views/components/week-view/example-card.html
  src/components/locale/locale.js
  src/components/week-view/week-view.js
Labels: needs qa
