Repository infor-design/enterprise, pull requests merged in 2023-10, with the labels that each got.

#7997 7554 - Date column filter locale setting
  app/views/components/datagrid/test-filter-custom-date.html
  docs/CHANGELOG.md
  src/components/datepicker/_datepicker.scss
Labels: needs qa

#8007 7756 - searchfield no results
  docs/CHANGELOG.md
  src/components/autocomplete/autocomplete.js
  src/components/popupmenu/_popupmenu.scss
  src/components/popupmenu/popupmenu.js
  src/components/searchfield/searchfield.js
Labels: needs qa

#8009 7843 - Fix card/widget header alignment in RTL mode
  docs/CHANGELOG.md
  src/components/cards/_cards-new.scss
  src/components/cards/_cards.scss
Labels: needs qa

#8013 518 - Add title case
  app/views/components/emptymessage/example-widgets.html
  app/views/components/emptymessage/test-centered-content.html
  app/views/components/icons/example-empty-widgets.html
  src/components/emptymessage/readme.md
Labels: needs qa

#8008 7824- Weekview add event modal
  docs/CHANGELOG.md
  src/components/calendar/calendar-shared.js
  src/components/calendar/calendar.js
  src/components/week-view/week-view.js
Labels: needs qa

#7996 7962 - Fix "delete all" in firefox.
  docs/CHANGELOG.md
  src/components/popupmenu/popupmenu.js
  src/components/toolbar-flex/_toolbar-flex.scss
Labels: needs qa

#8014 7677 - Change popover to allow components with event handlers
  app/views/components/popover/test-nested.html
  src/components/tooltip/tooltip.js
  src/utils/dom.js
Labels: needs qa

#8006 7768 - Fix validation error icon position in RTL
  docs/CHANGELOG.md
  src/components/datagrid/_datagrid-new.scss
  src/components/datagrid/_datagrid.scss
  src/components/datagrid/datagrid.formatters.js
  src/components/datagrid/datagrid.js
Labels: status: wip :construction:, needs qa

#8034 7884 - Fix accordion inherited module nav accordion styles
  app/views/components/module-nav/example-with-accordion-in-page-container.html
  docs/CHANGELOG.md
  src/components/module-nav/module-nav.accordion.scss
Labels: needs qa

#8033 7988 - Fix spinbox increment button overflow.
  docs/CHANGELOG.md
  src/components/spinbox/_spinbox.scss
Labels: needs qa

#8039 8037 - Fix env for safari
  docs/CHANGELOG.md
  src/components/place/place.js
  src/components/popupmenu/popupmenu.js
  src/utils/environment.js
Labels: priority: high, needs qa

#8041 7854 - empty message alignment
  app/views/components/datagrid/test-emptymessage-no-icon.html
  docs/CHANGELOG.md
  src/components/datagrid/_datagrid.scss
  src/components/emptymessage/emptymessage.js
Labels: needs qa

#8049 7970 - Fix alignment of icons in tabs dropdown menu.
  docs/CHANGELOG.md
  src/components/popupmenu/_popupmenu.scss
  src/components/tabs/_tabs-new.scss
  src/components/tabs/_tabs.scss
Labels: needs qa

#8026 7840 - Added overnight event view when end time goes to next day
  app/data/events.json
  docs/CHANGELOG.md
  src/components/week-view/week-view.js
Labels: needs qa

#8030 8019 - ModuleNav Added click out to collapse
  app/views/components/module-nav/example-index.html
  docs/CHANGELOG.md
  src/components/module-nav/module-nav.js
  src/components/module-nav/module-nav.scss
  src/components/module-nav/module-nav.searchfield.scss
  src/components/personalize/personalize.js
  src/components/personalize/personalize.styles.js
  src/components/searchfield/_searchfield.scss
  test/components/module-nav/module-nav-api-func-test.js
Labels: type: patch, priority: high, needs qa, needs design review

#8055 7977 - Fix primary button hover styling.
  docs/CHANGELOG.md
  src/components/button/_button-new.scss
Labels: needs qa

#8057 8056 - Fix quad widget width
  docs/CHANGELOG.md
  src/components/homepage/_homepage.scss
Labels: needs qa

#8001 5119 - locale exclamation mark non english (locale)
  docs/CHANGELOG.md
  src/components/personalize/personalize.styles.js
  src/components/tabs-header/_tabs-header-new.scss
  src/components/tabs-vertical/_tabs-vertical-new.scss
  src/components/tabs-vertical/_tabs-vertical.scss
Labels: needs qa

#8050 7982 - Fix process indicator icon sizing to remove gaps.
  docs/CHANGELOG.md
  src/components/processindicator/_processindicator-new.scss
  src/components/processindicator/_processindicator.scss
  src/components/timeline/_timeline-new.scss
Labels: needs qa

#8064 8063 - Add fixes to keep settings menu visible
  docs/CHANGELOG.md
  src/components/module-nav/module-nav.js
  src/components/module-nav/module-nav.settings.scss
Labels: type: patch, priority: high, needs qa

#8070 8058 - Datagrid Expandable Row Updates
  app/views/components/datagrid/test-expandable-row-editable-with-summary.html
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.formatters.js
  src/components/datagrid/datagrid.js
Labels: priority: high, needs qa

#8069 7928 - Datagrid ToolbarFlex Setting
  app/views/components/datagrid/test-toolbar-options.html
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.js
  src/components/toolbar-flex/_toolbar-flex.scss
  src/components/toolbar-flex/toolbar-flex.js
  test/components/header/header-puppeteer-visual-test.js
Labels: needs qa

#8089 8084 - Fix contextual toolbar styles
  docs/CHANGELOG.md
  src/components/toolbar/_toolbar.scss
  src/themes/theme-classic-contrast.scss
  src/themes/theme-new-contrast.scss
Labels: needs qa

#8079 7955 - Tabs Radios Overflow
  app/views/components/tabs/example-enable-disable-individual-tabs.html
  docs/CHANGELOG.md
  src/components/radios/_radios.scss
  src/components/tabs-header/_tabs-header-new.scss
Labels: needs qa

#8099 8081 - Fix cards menu button positioning for no header.
  docs/CHANGELOG.md
  src/components/cards/_cards-new.scss
  src/components/cards/_cards.scss
Labels: needs qa

#8091 8082 - Fix disabled radio button dot.
  docs/CHANGELOG.md
  src/components/radios/_radios.scss
  src/themes/theme-new-contrast.scss
  src/themes/theme-new-light.scss
Labels: needs qa

#8011 7974 - Fix disappearing popup borders.
  docs/CHANGELOG.md
  src/components/calendar/_calendar-toolbar.scss
  src/components/datepicker/_datepicker.scss
  src/components/monthview/_monthview.scss
  src/components/popupmenu/_popupmenu.scss
Labels: needs qa

#8107 7874 - Barstack Legend Space
  docs/CHANGELOG.md
  src/components/bar/bar.js
Labels: needs qa

#8054 7947 - Adjusted icon colors in classic
  docs/CHANGELOG.md
  src/components/header/_header-new.scss
  src/components/header/_header.scss
  src/components/personalize/personalize.styles.js
  src/components/searchfield/_searchfield-toolbar.scss
  src/components/searchfield/searchfield.js
  src/components/toolbar-flex/_toolbar-flex-searchfield.scss
Labels: needs qa

#8124 7845 - Pie/Donut Legend Item Select
  app/views/components/datagrid/example-filter.html
  docs/CHANGELOG.md
  src/components/charts/_charts.scss
  src/components/charts/charts.js
  src/components/popupmenu/_popupmenu.scss
  src/components/popupmenu/popupmenu.js
Labels: needs qa

#8106 NG1549 - Additional check for select row when datagrid has grouping and filter
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.js
Labels: needs qa

#8048 7922 - Alabaster Cleanup Round 4
  docs/CHANGELOG.md
  src/components/personalize/personalize.js
  src/components/tabs-module/_tabs-module-new.scss
  src/components/tabs-multi/_multi-tabs-new.scss
  src/components/tabs-vertical/_tabs-vertical.scss
  src/themes/theme-new-dark.scss
Labels: needs qa, needs design review

#8123 7927 - Weekview Selected Day
  docs/CHANGELOG.md
  src/components/week-view/week-view.js
Labels: needs qa

#8131 8121 - Add fix for counts
  src/components/counts/_counts.scss
Labels: needs qa

#8119 7957 - Fix slider console error.
  docs/CHANGELOG.md
  src/components/slider/_slider.scss
  src/components/slider/slider.js
Labels: needs qa

#8126 7923 - Additional check for modal width
  app/views/components/datagrid/test-contextualactionpanel.html
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.js
Labels: needs qa
