Repository infor-design/enterprise, pull requests merged in 2023-08, with the labels that each got.

#7732 7628 - Link Component
  app/views/components/link/example-index.html
  scripts/data/expected-files.json
  src/behaviors/initialize/initialize.js
  src/components/cards/_cards-new.scss
  src/components/components.jquery.js
  src/components/components.js
  src/components/link/_link.scss
  src/components/link/link.jquery.js
  src/components/link/link.js
  src/components/listview/_listview.scss
  src/core/_config.scss
  src/core/_controls-new.scss
  src/core/_controls.scss
  src/themes/theme-classic-contrast.scss
  src/themes/theme-classic-dark.scss
  src/themes/theme-new-contrast.scss
  src/themes/theme-new-dark.scss
Labels: needs qa, needs design review

#7735 7556 - Popupmenu Closing Behavior
  app/views/components/popupmenu/test-multiselect-singleselect.html
  docs/CHANGELOG.md
  src/components/popupmenu/popupmenu.js
  test/components/autocomplete/autocomplete-puppeteer-test.js
  test/components/datagrid/datagrid-puppeteer-test.js
  test/components/searchfield/searchfield-api-func-test.js
Labels: needs qa

#7736 7607 - Fix button icon hover background color when rows are selected
  docs/CHANGELOG.md
  src/components/datagrid/_datagrid.scss
  src/core/_config.scss
Labels: needs qa

#7738 7586/7737 - Fix colors in dark and contrast mode
  docs/CHANGELOG.md
  src/components/button/_button-new.scss
  src/components/tooltip/_tooltip.scss
  src/core/_config.scss
  src/themes/theme-new-dark.scss
Labels: needs qa

#7754 7753/1525 - Add module nav fixes
  docs/CHANGELOG.md
  src/components/module-nav/module-nav.js
  src/components/personalize/personalize.js
  src/themes/theme-new-dark.scss
Labels: type: patch, needs qa

#7755 7684 - Fixed bug where going to next didn't render the complete week
  docs/CHANGELOG.md
  src/components/week-view/week-view.js
  test/components/week-view/week-view-api-func-test.js
Labels: needs qa

#7758 7600 - Field Filter Dropdown Border
  docs/CHANGELOG.md
  src/components/field-filter/_field-filter-new.scss
Labels: needs qa

#7773 7628. Style adjustments for classic and adding tooltip on list when text overflows
  app/views/components/link/example-index.html
  src/components/listview/_listview.scss
  src/components/listview/listview.js
Labels: needs qa

#7778 7770 - Adjust padding in module nav
  app/views/components/module-nav/example-index.html
  docs/CHANGELOG.md
  src/components/module-nav/module-nav.accordion.scss
  src/components/module-nav/module-nav.scss
  src/core/_config.scss
Labels: type: patch, needs qa

#7775 7497 - Added text-wrap class
  app/views/components/css-utilities/example-index.html
  docs/CHANGELOG.md
  src/core/_css-utilities.scss
Labels: needs qa

#7765 7762/7760 -Add fixes for editor and color picker
  docs/CHANGELOG.md
  src/components/datepicker/datepicker.js
  src/components/popupmenu/popupmenu.js
Labels: needs qa

#7767 Allow defaultFilterOperator to be honored for date and time columns
  app/views/components/datagrid/test-filter-with-default-operator.html
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.js
Labels: type: patch, needs qa

#7771 1535 - Module Nav Option to disable search
  app/views/components/module-nav/example-no-dropdown-search.html
  docs/CHANGELOG.md
  src/components/module-nav/module-nav.switcher.js
Labels: type: patch, needs qa, focus: module nav

#7794 7786 - Module Nav: Add `enableOutsideClick` setting for collapse/hide when page content is clicked
  app/views/components/module-nav/example-index.html
  docs/CHANGELOG.md
  src/components/module-nav/module-nav.js
Labels: type: patch, priority: high, focus: module nav

#7798 7785 - Bump `ids-identity` version (accept new icons)
  package-lock.json
  package.json
Labels: type: patch, priority: high

#7774 7731 - Fixed hyperlink focus style in completion chart
  docs/CHANGELOG.md
  src/components/completion-chart/_completion-chart.scss
Labels: needs qa

#7784 6695 - Adjusted height for go button
  docs/CHANGELOG.md
  src/components/header/_header-new.scss
  src/components/header/_header.scss
  src/components/searchfield/_searchfield.scss
Labels: needs qa

#7789 7669 - Updated example page in tooltip
  app/views/components/tooltip/example-extra-css-class.html
  docs/CHANGELOG.md
Labels: needs qa

#7799 7528 - Datepicker Range December
  docs/CHANGELOG.md
  src/components/monthview/monthview.js
Labels: needs qa

#7790 7616 - Adjusted width of icons
  docs/CHANGELOG.md
  src/components/icons/_icons-new.scss
  src/components/icons/_icons.scss
Labels: needs qa

#7780 7571 - Added swatch bar on colorpicker button
  docs/CHANGELOG.md
  src/components/button/_button.scss
  src/components/editor/_editor-new.scss
  src/components/editor/editor.js
Labels: needs qa

#7817 7661 - Add docs for badge usage and alerts
  app/views/components/badges/example-index.html
  app/views/components/icons/example-status-colors.html
  docs/CHANGELOG.md
  src/components/alerts/readme.md
  src/components/badges/readme.md
  src/components/icons/_icons.scss
  src/components/icons/readme.md
  src/components/tag/readme.md
Labels: needs qa

#7812 7763 - Adjusted dropdown text in Firefox
  docs/CHANGELOG.md
  src/components/dropdown/_dropdown-new.scss
  src/components/dropdown/_dropdown.scss
Labels: needs qa

#7805 7752 - Added additional check for formatNumber
  docs/CHANGELOG.md
  src/utils/number.js
Labels: needs qa

#7830 7724 - Fix circlepager inside of a card
  app/views/components/circlepager/example-mobile.html
  docs/CHANGELOG.md
Labels: needs qa

#7802 7787 - Change file upload copy
  docs/CHANGELOG.md
  src/components/fileupload/_fileupload-new.scss
  src/components/fileupload/_fileupload.scss
  src/components/locale/cultures/en-US.js
  src/themes/theme-new-dark.scss
Labels: needs qa

#7829 7722 - fix legend and labels position in column stacked
  docs/CHANGELOG.md
  src/components/charts/_charts.scss
Labels: needs qa

#7835 7818 - Fix uncaught error
  docs/CHANGELOG.md
  src/components/calendar/calendar-toolbar.js
Labels: needs qa

#7837 7836 - Fix image size
  docs/CHANGELOG.md
  src/components/images/_images.scss
Labels: needs qa

#7781 7505 - Hero Widget Alabaster
  src/components/homepage/_homepage.scss
  src/components/personalize/personalize.styles.js
  src/core/_config.scss
  src/themes/theme-classic-contrast.scss
  src/themes/theme-classic-dark.scss
  src/themes/theme-new-contrast.scss
  src/themes/theme-new-dark.scss
Labels: needs qa, needs design review

#7825 7811 - Fix on Slate's personalization header text color
  docs/CHANGELOG.md
  src/components/personalize/personalize.styles.js
  src/utils/color.js
Labels: needs qa

#7833 7750 - Datagrid Filter List Intermittent
  docs/CHANGELOG.md
  src/components/popupmenu/popupmenu.js
Labels: needs qa

#7831 7819 - Use a different selector in homepage
  docs/CHANGELOG.md
  src/components/homepage/homepage.js
Labels: needs qa

#7839 7838 - Fix listview links
  docs/CHANGELOG.md
  src/components/listview/_listview.scss
Labels: needs qa

#7841 7661 - Change badge size by design
  app/views/components/icons/example-status-colors.html
  app/views/components/listview/example-card.html
  app/views/components/stats/example-index.html
  docs/CHANGELOG.md
  src/components/badges/_badges-new.scss
  src/components/badges/_badges.scss
  src/components/icons/_icons.scss
  src/components/link/readme.md
  src/components/stats/_stats.scss
  src/components/stats/readme.md
  test/components/tag/tag-puppeteer-visual-test.js
Labels: needs qa, needs design review

#7842 7679 - Popover Issue
  app/views/components/popover/test-popover-textarea.html
  docs/CHANGELOG.md
  src/components/tooltip/tooltip.js
Labels: needs qa

#7816 7606 - Add new editor designs
  app/views/components/editor/example-index.html
  docs/CHANGELOG.md
  src/components/button/_button-new.scss
  src/components/editor/_editor-new.scss
  src/components/editor/_editor.scss
  src/components/input/_input.scss
  src/core/_config.scss
  src/themes/theme-new-contrast.scss
  src/themes/theme-new-dark.scss
  src/themes/theme-new-light.scss
Labels: needs qa, needs design review

#7847 7822 - Added listcontextmenu event
  app/views/components/dropdown/example-contextmenu-event.html
  app/views/components/module-nav/example-index.html
  docs/CHANGELOG.md
  src/components/dropdown/dropdown.js
  src/components/personalize/personalize.js
  src/components/personalize/personalize.styles.js
Labels: type: patch, needs qa

#7853 7629 - Pager Pagesizes Overwrite
  app/views/components/datagrid/example-paging.html
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.js
  src/components/pager/pager.js
  test/components/datagrid/datagrid-settings-func-test.js
Labels: needs qa

#7855 7645 - Trigger the validation after clearing the input field
  docs/CHANGELOG.md
  src/components/fileupload/fileupload.js
Labels: needs qa

#7858 7747 - Set masthead height to 40px / remove info
  app/views/components/icons/example-status-colors.html
  docs/CHANGELOG.md
  src/components/grid/_grid.scss
  src/components/masthead/_masthead-new.scss
  src/components/masthead/_masthead.scss
Labels: needs qa

#7856 7677 - Fixes on issues in popover when opening and closing
  app/views/components/popover/test-nested.html
  docs/CHANGELOG.md
  src/components/textarea/textarea.js
Labels: needs qa

#7864 7862 - Change radius to 12px
  app/views/components/contextualactionpanel/example-cap-tabs-vertical-scroll.html
  docs/CHANGELOG.md
  src/components/badges/_badges.scss
  test/components/contextualactionpanel/contextualactionpanel-puppeteer-test.js
Labels: needs qa

#7872 7727 - weekview resize issue
  docs/CHANGELOG.md
  src/components/week-view/week-view.js
Labels: needs qa

#7844 7797 - Fix bar charts label were not visible
  docs/CHANGELOG.md
  src/components/bar/bar.js
Labels: priority: high, needs qa

#7871 7676 - Improve popover title
  docs/CHANGELOG.md
  src/components/tooltip/_tooltip.scss
Labels: needs qa

#7868 7659 - Add hitbox in radio component
  app/views/components/radios/example-hitbox.html
  docs/CHANGELOG.md
  src/components/radios/_radios.scss
Labels: needs qa, needs design review
