Repository infor-design/enterprise, pull requests merged in 2023-03, with the labels that each got.

#7313 7282 - Fix to not re-render the grid when disableClientFilter is set to true
  app/views/components/datagrid/test-filtering-violations.html
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.js
Labels: priority: high

#7326 7320 - Change default color back to azure
  app/views/components/personalize/example-color-theme-api.html
  app/views/components/personalize/example-form-landmark.html
  docs/CHANGELOG.md
  src/components/colors/_colors.scss
  src/components/counts/_counts.scss
  src/components/dropdown/_dropdown-new.scss
  src/components/header/_header.scss
  src/components/header/header.js
  src/components/hyperlinks/_hyperlinks.scss
  src/components/locale/cultures/en-US.js
  src/components/personalize/_personalize.scss
  src/components/personalize/personalize.js
  src/components/personalize/personalize.styles.js
  src/components/searchfield/_searchfield-toolbar.scss
  src/components/tabs-header/_tabs-header.scss
  src/components/theme/theme.js
  src/components/toolbar-flex/_toolbar-flex-searchfield.scss
  src/core/_config.scss
  src/themes/theme-classic-contrast.scss
  src/themes/theme-classic-dark.scss
  src/themes/theme-new-contrast.scss
  src/themes/theme-new-dark.scss
  src/themes/theme-new-light.scss
Labels: priority: critical

#7334 7320 - Additional fixes
  app/views/components/header/example-subheader.html
  app/views/components/homepage/example-hero-widget.html
  app/views/components/homepage/example-widget-two-column.html
  app/views/components/homepage/test-hero-widget-calculate-height.html
  src/components/header/_header.scss
  src/components/header/header.js
  src/components/homepage/_homepage.scss
  src/components/personalize/_personalize.scss
  src/components/personalize/personalize.js
  src/components/personalize/personalize.styles.js
  src/core/_config.scss
  src/themes/theme-classic-contrast.scss
  src/themes/theme-new-contrast.scss
  src/themes/theme-new-light.scss
  test/components/breadcrumb/breadcrumb-puppeteer-test.js
  test/components/textarea/textarea-puppeteer-test.js
Labels: priority: high

#7363 7340 - More Fixes For Alabaster (no css class)Add patches for alabaster
  .vscode/settings.json
  .vscode/spellright.dict
  app/package.json
  app/views/components/header/example-breadcrumbs-alternate.html
  app/views/components/header/example-drilldown.html
  app/views/components/header/example-emphasize-id.html
  app/views/components/header/example-emphasize-page-title.html
  app/views/components/header/example-eyebrow.html
  app/views/components/header/example-personalize-subheader.html
  app/views/components/header/example-record-id.html
  app/views/components/header/example-wizard-alternate.html
  app/views/components/personalize/example-color-theme-api.html
  app/views/components/personalize/example-form-landmark2.html
  app/views/components/personalize/example-form3-short.html
  app/views/components/personalize/example-form3.html
  app/views/components/personalize/test-form2-short.html
  app/views/includes/header-go-back-trigger.html
  app/views/includes/header-no-actionbutton.html
  docs/CHANGELOG.md
  docs/QA.md
  src/components/applicationmenu/_applicationmenu-new.scss
  src/components/applicationmenu/readme.md
  src/components/badges/_badges.scss
  src/components/breadcrumb/_breadcrumb.scss
  src/components/button/_button-new.scss
  src/components/button/_button.scss
  src/components/colors/_colors.scss
  src/components/dropdown/_dropdown-new.scss
  src/components/header/_header-new.scss
  src/components/header/_header.scss
  src/components/header/header.js
  src/components/header/readme.md
  src/components/homepage/_homepage.scss
  src/components/hyperlinks/_hyperlinks.scss
  src/components/monthview/_monthview.scss
  src/components/personalize/_personalize.scss
  src/components/personalize/personalize.js
  src/components/personalize/personalize.styles.js
  src/components/searchfield/_searchfield-toolbar.scss
  src/components/tabs-header/_tabs-header-new.scss
  src/components/tabs-header/_tabs-header.scss
  src/components/tabs/_tabs-new.scss
  src/components/tabs/_tabs.scss
  src/components/tabs/tabs.js
  src/components/wizard/_wizard.scss
  src/core/_config.scss
  src/themes/theme-classic-contrast.scss
  src/themes/theme-classic-dark.scss
  src/themes/theme-new-contrast.scss
  src/themes/theme-new-dark.scss
  test/components/applicationmenu/applicationmenu-func-test.js
Labels: needs qa
