Repository infor-design/enterprise, pull requests merged in 2023-06, with the labels that each got.

#7564 7535 - editor buttons hover style
  docs/CHANGELOG.md
  src/components/button/_button-new.scss
  src/components/editor/_editor.scss
  src/core/_config.scss
  src/themes/theme-new-contrast.scss
Labels: needs design review

#7533 6956 - Adjusted the table's width to fill the container of the datagrid, ensuring proper alignment
  docs/CHANGELOG.md
  src/components/datagrid/_datagrid.scss
  src/components/modal/_modal.scss
Labels: needs qa

#7549 7386 - Implement Module Nav Component
  app/views/components/module-nav/example-empty-state.html
  app/views/components/module-nav/example-index.html
  app/views/components/module-nav/example-six-levels-icons.html
  app/views/components/module-nav/example-six-levels.html
  app/views/components/module-nav/layout.html
  docs/CHANGELOG.md
  src/behaviors/initialize/initialize.js
  src/components/accordion/_accordion-mixins.scss
  src/components/accordion/_accordion-new.scss
  src/components/accordion/_accordion.scss
  src/components/accordion/accordion.js
  src/components/accordion/readme.md
  src/components/applicationmenu/applicationmenu.js
  src/components/autocomplete/autocomplete.js
  src/components/button/_button-new.scss
  src/components/components.jquery.js
  src/components/components.js
  src/components/dropdown/_dropdown.scss
  src/components/dropdown/dropdown.js
  src/components/locale/cultures/en-US.js
  src/components/module-nav/module-nav.accordion.scss
  src/components/module-nav/module-nav.common.js
  src/components/module-nav/module-nav.common.scss
  src/components/module-nav/module-nav.dropdown.scss
  src/components/module-nav/module-nav.jquery.js
  src/components/module-nav/module-nav.js
  src/components/module-nav/module-nav.scss
  src/components/module-nav/module-nav.searchfield.scss
  src/components/module-nav/module-nav.settings.jquery.js
  src/components/module-nav/module-nav.settings.js
  src/components/module-nav/module-nav.settings.scss
  src/components/module-nav/module-nav.switcher.jquery.js
  src/components/module-nav/module-nav.switcher.js
  src/components/module-nav/module-nav.switcher.scss
  src/components/module-nav/readme.md
  src/components/popupmenu/_popupmenu.scss
  src/components/popupmenu/popupmenu.js
  src/components/tooltip/tooltip.js
  src/components/visibility/_visibility.scss
  src/core/_config.scss
  src/core/_controls-new.scss
  src/core/_controls.scss
  src/core/_mixins.scss
  src/utils/accordion-search-utils.js
  src/utils/behaviors.js
  test/components/dropdown/dropdown-updates-events-func-test.js
  test/components/module-nav/module-nav-api-func-test.js
Labels: needs qa

#7558 7274 - Added setting to insert and replace next character if maximum length is already reached
  app/views/components/input/example-index.html
  docs/CHANGELOG.md
  src/components/mask/mask-input.js
Labels: needs qa

#7563 7007 - Images with Click Handler
  app/views/components/datagrid/test-form-images-actionable.html
  app/views/components/images/test-image-click.html
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.formatters.js
  src/components/datagrid/datagrid.js
  src/components/images/_images.scss
Labels: needs qa

#7566 7491/5886 - Add translation fixes
  app/views/components/locale/test-extend-messages.html
  docs/CHANGELOG.md
  src/components/dropdown/dropdown.js
  src/components/locale/cultures/fr-CA.js
  src/components/locale/cultures/pt-BR.js
  src/components/locale/locale.js
  test/components/locale/locale-func-test.js
Labels: needs qa

#7581 7580/7579 - Additional Card fixes
  app/views/components/homepage/example-editable.html
  docs/CHANGELOG.md
  src/components/cards/_cards-new.scss
  src/components/cards/_cards.scss
  src/components/homepage/_homepage.scss
Labels: type: patch

#7569 7467 - Fixes in disabled datagrid filters
  app/views/components/datagrid/test-filter-disabled.html
  docs/CHANGELOG.md
  src/components/datagrid/_datagrid.scss
  src/components/timepicker/timepicker.js
  src/themes/theme-new-contrast.scss
Labels: needs qa

#7577 7486 - Fix on incorrect row updates on adding a new row to the next page
  app/views/components/datagrid/test-selected-rows-addnew.html
  docs/CHANGELOG.md
  src/components/datagrid/_datagrid.scss
  src/components/datagrid/datagrid.js
  test/components/datagrid/datagrid-puppeteer-test.js
Labels: needs qa

#7584 7506 - stats component
  app/views/components/stats/example-index.html
  docs/CHANGELOG.md
  scripts/data/expected-files.json
  src/components/cards/_cards-new.scss
  src/components/cards/_cards.scss
  src/components/cards/cards.js
  src/components/stats/_stats.scss
  src/core/_config.scss
  src/core/_controls-new.scss
  src/core/_controls.scss
  src/themes/theme-classic-dark.scss
  src/themes/theme-new-contrast.scss
  src/themes/theme-new-dark.scss
  src/themes/theme-new-light.scss
  src/utils/selectable.jquery.js
Labels: needs qa, needs design review

#7592 7205 - lookup width constraint
  app/views/components/lookup/test-lookup-overflow.html
  docs/CHANGELOG.md
  src/components/lookup/_lookup.scss
  src/components/searchfield/_searchfield.scss
Labels: needs qa

#7622 7502 - Fix dropdown icon overlapping the field in RTL
  docs/CHANGELOG.md
  src/components/dropdown/_dropdown-new.scss
Labels: needs qa

#7620 7585 - CAP Overflow
  docs/CHANGELOG.md
  src/components/modal/modal.js
Labels: needs qa

#7633 NG1477 - Module Nav Switcher: API improvements
  app/views/components/module-nav/example-index.html
  docs/CHANGELOG.md
  src/components/accordion/accordion.js
  src/components/module-nav/module-nav.common.js
  src/components/module-nav/module-nav.js
  src/components/module-nav/module-nav.switcher.js
  src/components/module-nav/module-nav.switcher.scss
Labels: type: patch, needs qa

#7630 7266 - column stacked and label alignment
  docs/CHANGELOG.md
  src/components/column/column.js
  test/components/column/column-stacked-puppeteer-test.js
Labels: needs qa

#7634 5018 - Popupmenu Placement when Parent Element is outside of viewport
  app/views/components/popupmenu/test-menubutton-viewport.html
  docs/CHANGELOG.md
  src/components/place/place.js
Labels: needs qa

#7635 7609 - menu items alabaster
  docs/CHANGELOG.md
  src/components/personalize/personalize.styles.js
Labels: needs qa

#7640 7639 - Add alignment fix for icons
  docs/CHANGELOG.md
  src/components/modal/_modal.scss
Labels: needs qa

#7646 7642 - Fix search icon position in toolbar
  docs/CHANGELOG.md
  src/components/searchfield/_searchfield.scss
Labels: needs qa

#7653 1360 - Fix empty message size
  docs/CHANGELOG.md
  src/components/icons/_icons-new.scss
Labels: needs qa

#7621 7546 - Fix UI of listview with filters
  app/views/components/listview/example-filters.html
  docs/CHANGELOG.md
  src/components/cards/_cards-new.scss
  src/components/listview/_listview.scss
Labels: needs qa

#7651 7648 - Fix progress bar color
  docs/CHANGELOG.md
  src/components/toast/_toast.scss
  src/core/_config.scss
  src/themes/theme-classic-dark.scss
  src/themes/theme-new-dark.scss
Labels: needs qa

#7641 7499 - Added z-index for empty filter wrapper
  app/views/components/datagrid/test-change-show-select-all-checkbox.html
  docs/CHANGELOG.md
  src/components/datagrid/_datagrid.scss
Labels: needs qa
