Repository infor-design/enterprise, pull requests merged in 2023-07, with the labels that each got.

#7658 7657 - Change to title case and remove console log
  app/views/components/pager/example-standalone.html
  app/views/components/stats/example-index.html
  src/components/cards/_cards-new.scss
  src/components/homepage/homepage.js
  src/components/place/place.js
  src/components/stats/_stats.scss
Labels: needs qa

#7649 7565 - border color accordion header
  docs/CHANGELOG.md
  src/components/applicationmenu/_applicationmenu-new.scss
  src/core/_config.scss
Labels: type: patch, priority: high, needs qa

#7588 7507 - New classes and example page for listview card
  app/views/components/listview/example-card.html
  src/components/cards/_cards-new.scss
  src/components/cards/_cards.scss
  src/components/cards/cards.js
  src/components/colors/_colors.scss
  src/components/colors/readme.md
  src/components/homepage/_homepage.scss
  src/components/homepage/homepage.js
  src/components/icons/_icons.scss
  src/components/icons/readme.md
  src/components/listview/_listview.scss
  src/components/listview/listview.js
  src/components/listview/readme.md
  src/themes/theme-classic-dark.scss
  src/themes/theme-new-dark.scss
Labels: needs qa, needs design review

#7663 7624 - Add new color palette (and tweaks)
  app/views/components/cards/example-expandable-cards.html
  app/views/components/css-utilities/example-index.html
  app/views/components/monthview/example-inpage.html
  docs/CHANGELOG.md
  package-lock.json
  package.json
  src/components/breadcrumb/_breadcrumb.scss
  src/components/colors/_colors.scss
  src/components/column/column.js
  src/components/personalize/personalize.js
  src/components/personalize/personalize.styles.js
  src/components/typography/_typography-new.scss
  src/core/_config.scss
  src/themes/theme-classic-contrast.scss
  src/themes/theme-classic-dark.scss
  src/themes/theme-new-contrast.scss
  src/themes/theme-new-dark.scss
  src/themes/theme-new-light.scss
  test/components/calendar/calendar-puppeteer-test.js
  test/components/header/header-puppeteer-visual-test.js
  test/components/swipe-action/swipe-action-puppeteer-visual-test.js
  test/components/treemap/treemap-puppeteer-visual-test.js
  test/components/validation/validation-e2e-test.js
  test/components/wizard/wizard-puppeteer-visual-test.js
Labels: needs qa

#7665 7611 - Fixed a bug where disabled buttons in cells were hoverable
  docs/CHANGELOG.md
  src/components/button/_button-new.scss
  src/themes/theme-classic-dark.scss
  src/themes/theme-classic-light.scss
Labels: needs qa

#7664 7464 - dropdown mouseenter and keydown selection issue
  docs/CHANGELOG.md
  src/components/dropdown/dropdown.js
Labels: needs qa

#7667 7562 - Fixed a bug in datepicker filter icon's hover state and alignment
  docs/CHANGELOG.md
  src/components/button/_button-new.scss
  src/components/datagrid/_datagrid-new.scss
Labels: needs qa

#7672 NG1477 - Add more Module Nav API improvements
  docs/CHANGELOG.md
  src/components/accordion/accordion.js
  src/components/module-nav/module-nav.common.js
  src/components/module-nav/module-nav.js
  src/components/module-nav/module-nav.switcher.js
Labels: type: patch, needs qa

#7673 7636 - Updated hover style for button in listview
  docs/CHANGELOG.md
  src/components/cards/_cards.scss
Labels: needs qa

#7675 7637 - Fixed height for card button
  docs/CHANGELOG.md
  src/components/cards/_cards.scss
Labels: needs qa

#7670 7383 - Updated popupmenu color styles
  docs/CHANGELOG.md
  src/components/contextualactionpanel/_contextualactionpanel.scss
Labels: needs qa

#7688 N/A - Fix d3.values is not a function in line chart
  app/views/components/line/example-axis-ticks.html
  app/views/components/line/test-axis-ticks-date-range.html
Labels: needs qa

#7692 7644 - Fix errors in column-stacked if there are no x-axis labels
  docs/CHANGELOG.md
  src/components/column/column.js
Labels: needs qa

#7701 7475 - Added ID check in event triggers
  app/views/components/message/test-nested.html
  docs/CHANGELOG.md
  src/components/message/message.js
  src/components/modal/modal.js
Labels: needs qa

#7703 7626 - Fix misalignment of submenu icons
  docs/CHANGELOG.md
  src/components/popupmenu/_popupmenu.scss
Labels: needs qa

#7704 7561 - Page Pattern Search Field Full Width
  docs/CHANGELOG.md
  src/components/listview/_listview.scss
Labels: needs qa

#7707 7693 - Added fix for stacked legend
  app/views/kitchen-sink.html
  docs/CHANGELOG.md
  src/components/bar/bar.js
Labels: needs qa

#7695 7654 - Fix rounding and zindex issue
  docs/CHANGELOG.md
  src/components/accordion/_accordion.scss
  src/components/module-nav/module-nav.scss
Labels: needs qa

#7705 7700 - WeekView Agenda Variant hide allDay row
  app/views/components/week-view/example-card.html
  app/views/components/week-view/example-stacked.html
  docs/CHANGELOG.md
  src/components/week-view/week-view.js
Labels: needs qa

#7714 NG1477 - Fix remaining lifecycle/settings issues
  app/views/components/module-nav/example-icon.html
  app/views/components/module-nav/example-one-pane.html
  src/components/module-nav/module-nav.common.js
  src/components/module-nav/module-nav.js
  src/components/module-nav/module-nav.switcher.js
  src/utils/string.js
Labels: needs qa

#7712 7711 - Re fix for modal overflow issues
  app/views/components/modal/example-slider.html
  docs/CHANGELOG.md
  src/components/modal/_modal.scss
  src/components/modal/modal.js
  src/core/_config.scss
  src/themes/theme-classic-contrast.scss
  src/themes/theme-classic-dark.scss
  src/themes/theme-classic-light.scss
  src/themes/theme-new-contrast.scss
  src/themes/theme-new-dark.scss
  src/themes/theme-new-light.scss
Labels: type: patch, needs qa

#7710 7530 - Datagrid Default Operator For Lookup
  app/views/components/datagrid/test-filter-with-default-operator.html
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.js
Labels: type: patch

#7716 NG1499 - Tooltip Script Error
  app/views/components/tooltip/test-irregular-string.html
  docs/CHANGELOG.md
  src/components/tooltip/tooltip.js
Labels: needs qa

#7702 7570 - Fileupload Icon Alignment
  docs/CHANGELOG.md
  src/components/fileupload/_fileupload-new.scss
  src/components/fileupload/_fileupload.scss
  src/components/fileupload/fileupload.js
  src/themes/theme-classic-dark.scss
  src/themes/theme-new-dark.scss
Labels: needs qa

#7718 7463 - Fix missing borders when pasting html table inside of the editor
  docs/CHANGELOG.md
  src/components/editor/_editor.scss
Labels: needs qa

#7721 7623 - Updated color styles when notification is in subheader
  app/views/components/notification/test-insert-subheader.html
  docs/CHANGELOG.md
  src/components/personalize/personalize.styles.js
Labels: needs qa

#7725 7719 - Module Nav Fixes
  .vscode/spellright.dict
  app/views/components/accordion/example-index.html
  app/views/components/accordion/test-all-chevrons.html
  app/views/components/accordion/test-all-plus-minus.html
  app/views/components/applicationmenu/test-container.html
  app/views/components/applicationmenu/test-different-header-types.html
  app/views/components/applicationmenu/test-six-levels-icons.html
  app/views/components/applicationmenu/test-six-levels.html
  app/views/components/module-nav/example-empty-state.html
  app/views/components/module-nav/example-hidden.html
  app/views/components/module-nav/example-icon.html
  app/views/components/module-nav/example-index.html
  app/views/components/module-nav/example-not-filterable.html
  app/views/components/module-nav/example-one-pane.html
  app/views/components/module-nav/example-six-levels-icons.html
  app/views/components/module-nav/example-six-levels.html
  docs/CHANGELOG.md
  src/components/accordion/_accordion.scss
  src/components/accordion/accordion.js
  src/components/dropdown/_dropdown-new.scss
  src/components/dropdown/_dropdown.scss
  src/components/dropdown/dropdown.js
  src/components/locale/cultures/en-US.js
  src/components/module-nav/module-nav.accordion.scss
  src/components/module-nav/module-nav.common.js
  src/components/module-nav/module-nav.dropdown.scss
  src/components/module-nav/module-nav.js
  src/components/module-nav/module-nav.scss
  src/components/module-nav/module-nav.searchfield.scss
  src/components/module-nav/module-nav.switcher.js
  src/core/_config.scss
  src/themes/theme-classic-contrast.scss
  src/themes/theme-classic-dark.scss
  src/themes/theme-new-contrast.scss
  src/themes/theme-new-dark.scss
  test/components/accordion/accordion-puppeteer-test.js
  test/components/dropdown/dropdown-updates-events-func-test.js
  test/components/hierarchy/hierarchy-puppeteer-test.js
Labels: type: patch, priority: high, needs qa

#7728 NG1480 - Tab Item Sortable
  app/views/components/tabs-module/test-updated.html
  docs/CHANGELOG.md
  src/components/tabs/tabs.js
Labels: needs qa

#7674 7333 - Alabaster Cleanup
  app/views/components/tabs-header/example-index.html
  app/views/components/tabs-module/example-index.html
  app/views/components/tabs-multi/example-index.html
  app/views/components/tabs-vertical/example-index.html
  src/components/personalize/personalize.js
  src/components/personalize/personalize.styles.js
  src/components/tabs-header/_tabs-header-new.scss
  src/components/tabs-module/_tabs-module-new.scss
  src/components/tabs-module/_tabs-module.scss
  src/components/tabs-vertical/_tabs-vertical-new.scss
  src/components/tabs-vertical/_tabs-vertical.scss
  src/components/tabs/_tabs-new.scss
  src/components/tabs/tabs.js
  src/themes/theme-classic-dark.scss
  src/themes/theme-new-dark.scss
  test/components/locale/locale-puppeteer-visual-test.js
Labels: needs qa, needs design review

#7729 7465 - Header Text Disabled Dark Mode
  app/views/components/header/example-tabs-alternate.html
  docs/CHANGELOG.md
  src/components/tabs-header/_tabs-header-new.scss
  src/core/_config.scss
  src/themes/theme-classic-contrast.scss
  src/themes/theme-classic-dark.scss
  src/themes/theme-new-contrast.scss
  src/themes/theme-new-dark.scss
Labels: needs qa

#7730 7603 - Datepicker Date Range Render
  app/views/components/datepicker/test-modal-range.html
  docs/CHANGELOG.md
  src/components/modal/_modal.scss
Labels: needs qa
