Repository infor-design/enterprise, pull requests merged in 2023-05, with the labels that each got.

#7451 NG1435 - Timepicker Validation
  docs/CHANGELOG.md
  src/components/datepicker/datepicker.js
  src/components/textarea/textarea.js
  src/components/timepicker/timepicker.js
Labels: needs qa

#7469 7302 - Removed color style for other appmenu icons
  src/components/applicationmenu/_applicationmenu-new.scss
  src/components/personalize/personalize.styles.js
Labels: needs qa

#7472 7321 - Tabs Module Activate previous tab when active is removed from overflow menu
  docs/CHANGELOG.md
  src/components/personalize/personalize.styles.js
  src/components/tabs/tabs.js
Labels: needs qa

#7470 6837 - DemoApp Use FlexBox in Examples
  app/views/components/header/example-breadcrumbs-alternate.html
  app/views/components/header/example-breadcrumbs.html
  app/views/components/header/example-buttons-larger-search.html
  app/views/components/header/example-disabled-buttons.html
  app/views/components/header/example-drilldown.html
  app/views/components/header/example-emphasize-id.html
  app/views/components/header/example-emphasize-page-title.html
  app/views/components/header/example-eyebrow.html
  app/views/components/header/example-index.html
  app/views/components/header/example-long-title-no-button.html
  app/views/components/header/example-no-title-button.html
  app/views/components/header/example-non-collapsible-searchfield.html
  app/views/components/header/example-popupmenu.html
  app/views/components/header/example-record-id.html
  app/views/components/header/example-searchfield-expanded.html
  app/views/components/header/example-searchfield-full.html
  app/views/components/header/example-subheader.html
  app/views/components/header/example-tabs-alternate.html
  app/views/components/header/example-tabs-outbound-page1.html
  app/views/components/header/example-tabs.html
  app/views/components/header/example-toolbar.html
  app/views/components/header/example-wizard-alternate.html
  app/views/components/header/example-wizard.html
  app/views/components/header/test-autocomplete.html
  app/views/components/header/test-header-gauntlet.html
  app/views/components/header/test-togglebuttons.html
  app/views/components/masthead/test-different-button-types.html
  app/views/components/masthead/test-old-toolbar.html
  app/views/components/masthead/test-popups-on-each-side.html
  app/views/components/masthead/test-tooltips-on-buttons.html
  app/views/includes/header-actionbutton.html
  app/views/includes/header.html
  docs/CHANGELOG.md
  src/components/header/_header-new.scss
  test/components/datagrid/datagrid-puppeteer-test.js
  test/components/timepicker/timepicker-puppeteer-test.js
Labels: needs qa

#7478 7408 - Adjusted alignment for popupmenu icon buttons
  docs/CHANGELOG.md
  src/components/popupmenu/_popupmenu.scss
Labels: needs qa

#7492 7466 - Fix on header text not being readable due to color styles
  docs/CHANGELOG.md
  src/components/personalize/personalize.styles.js
Labels: needs qa

#7490 6033 - Clear rowstatus in tree node for clearRowError to work correctly
  app/views/components/datagrid/test-tree-rowstatus.html
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.js
Labels: needs qa

#7488 7373 - Weekview agenda variant
  app/views/components/week-view/example-card.html
  app/views/components/week-view/example-stacked.html
  docs/CHANGELOG.md
  src/components/datepicker/_datepicker.scss
  src/components/datepicker/datepicker.js
  src/components/monthview/_monthview.scss
  src/components/week-view/_week-view.scss
  src/components/week-view/week-view.js
  src/utils/date.js
  test/components/week-view/week-view-api-func-test.js
Labels: needs qa, needs design review

#7498 5887 - Added Comma translate option for locale for generating lists
  docs/CHANGELOG.md
  src/components/dropdown/dropdown.js
  src/components/locale/cultures/af-ZA.js
  src/components/locale/cultures/ar-EG.js
  src/components/locale/cultures/ar-SA.js
  src/components/locale/cultures/bg-BG.js
  src/components/locale/cultures/cs-CZ.js
  src/components/locale/cultures/da-DK.js
  src/components/locale/cultures/de-DE.js
  src/components/locale/cultures/el-GR.js
  src/components/locale/cultures/en-AU.js
  src/components/locale/cultures/en-GB.js
  src/components/locale/cultures/en-IN.js
  src/components/locale/cultures/en-NZ.js
  src/components/locale/cultures/en-US.js
  src/components/locale/cultures/en-ZA.js
  src/components/locale/cultures/es-419.js
  src/components/locale/cultures/es-AR.js
  src/components/locale/cultures/es-ES.js
  src/components/locale/cultures/es-MX.js
  src/components/locale/cultures/es-US.js
  src/components/locale/cultures/et-EE.js
  src/components/locale/cultures/fi-FI.js
  src/components/locale/cultures/fr-CA.js
  src/components/locale/cultures/fr-FR.js
  src/components/locale/cultures/he-IL.js
  src/components/locale/cultures/hi-IN.js
  src/components/locale/cultures/hr-HR.js
  src/components/locale/cultures/hu-HU.js
  src/components/locale/cultures/id-ID.js
  src/components/locale/cultures/it-IT.js
  src/components/locale/cultures/ja-JP.js
  src/components/locale/cultures/ko-KR.js
  src/components/locale/cultures/la-IT.js
  src/components/locale/cultures/lt-LT.js
  src/components/locale/cultures/lv-LV.js
  src/components/locale/cultures/ms-bn.js
  src/components/locale/cultures/ms-my.js
  src/components/locale/cultures/nb-NO.js
  src/components/locale/cultures/nl-NL.js
  src/components/locale/cultures/nn-NO.js
  src/components/locale/cultures/no-NO.js
  src/components/locale/cultures/pl-PL.js
  src/components/locale/cultures/pt-BR.js
  src/components/locale/cultures/pt-PT.js
  src/components/locale/cultures/ro-RO.js
  src/components/locale/cultures/ru-RU.js
  src/components/locale/cultures/sk-SK.js
  src/components/locale/cultures/sl-SI.js
  src/components/locale/cultures/sv-SE.js
  src/components/locale/cultures/th-TH.js
  src/components/locale/cultures/tl-PH.js
  src/components/locale/cultures/tr-TR.js
  src/components/locale/cultures/uk-UA.js
  src/components/locale/cultures/vi-VN.js
  src/components/locale/cultures/zh-CN.js
  src/components/locale/cultures/zh-Hans.js
  src/components/locale/cultures/zh-Hant.js
  src/components/locale/cultures/zh-TW.js
  test/components/multiselect/multiselect-api-func-test.js
Labels: needs qa

#7504 5906 - Added short and abbreviated name options for the data
  app/views/components/line/test-long-labels.html
  docs/CHANGELOG.md
  src/components/line/line.js
Labels: needs qa

#7500 6311 - Removed overflow none style for dropdown modal
  app/views/components/datagrid/test-dropdown-scroll.html
  docs/CHANGELOG.md
  src/components/dropdown/dropdown.js
Labels: needs qa

#7515 7413 - Fix background color and hover bg color of column grouped headers in light header
  app/views/components/datagrid/example-grouped-headers-is-list.html
  docs/CHANGELOG.md
  src/components/datagrid/_datagrid-new.scss
Labels: needs qa

#7514 7431 - Fix icons and palette icons visibility in dark mode
  docs/CHANGELOG.md
  src/components/dropdown/_dropdown.scss
  src/core/_config.scss
  src/themes/theme-classic-dark.scss
  src/themes/theme-new-dark.scss
Labels: needs qa

#7518 Fix: Add regression fix for icons in menus
  src/components/popupmenu/_popupmenu.scss
Labels: type: patch, type: regression bug :leftwards_arrow_with_hook:, needs qa

#7525 Chore: More widget fixes
  app/views/components/cards/example-workspace-widgets.html
  src/components/listview/_listview-new.scss
  src/components/typography/_typography.scss
  src/core/_config.scss
  src/themes/theme-new-contrast.scss
Labels: type: patch

#7526 NG#1463 - add defaultTickCount setting to automatically add ticks when there are no dataset values
  app/views/components/bar/example-with-zero-value.html
  docs/CHANGELOG.md
  src/components/bar/_bar.scss
  src/components/bar/bar.js
Labels: needs qa

#7529 Fix: Fix icon and alignment
  docs/CHANGELOG.md
  src/components/listview/_listview.scss
  src/components/pager/_pager-new.scss
  src/components/searchfield/_searchfield-toolbar-new.scss
Labels: needs qa

#7539 1489 - Android enterkeyhint
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.js
  src/components/lookup/readme.md
Labels: needs qa

#7531 7428 - Fix on showColumn not working properly with frozen columns
  docs/CHANGELOG.md
  src/components/datagrid/_datagrid.scss
  src/components/datagrid/datagrid.js
Labels: needs qa

#7540 7421 - Fix tab overflow error
  src/components/tabs/tabs.js
Labels: type: patch

#7537 7536 - Fix textarea throwing error
  docs/CHANGELOG.md
  src/components/textarea/textarea.js
Labels: type: patch, priority: high

#7547 Misc - Regression fixes
  docs/CHANGELOG.md
  src/components/listview/_listview-new.scss
  src/components/modal/_modal-new.scss
  src/components/modal/_modal.scss
  src/components/toolbar/_toolbar-new.scss
  src/core/_config.scss
Labels: type: patch

#7551 7362 - Add fix to close colorpicker
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.js
Labels: needs qa

#7552 7550 - Fix x alignment on old toolbar
  docs/CHANGELOG.md
  src/components/toolbar/_toolbar-new.scss
Labels: needs qa

#7553 7516 - Add fixes to tab selected color
  docs/CHANGELOG.md
  src/components/personalize/personalize.js
  src/components/personalize/personalize.styles.js
  src/components/searchfield/_searchfield-toolbar.scss
Labels: needs qa
