Repository infor-design/enterprise, pull requests merged in 2024-05, with the labels that each got.

#8664 8663 - Fix serializer function for tree datagrid
  app/views/components/datagrid/test-tree-serializer.html
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.js
  src/components/datagrid/readme.md
Labels: ready for qa

#8650 8530 - Calendar Day View Event Render
  app/data/events.json
  app/views/components/calendar/test-start-end-hour.html
  docs/CHANGELOG.md
  src/components/calendar/_calendar-new.scss
  src/components/calendar/_calendar.scss
  src/components/calendar/calendar.js
  src/components/week-view/week-view.js
Labels: priority: high

#8670 8640 - Fix incorrect height of homepage
  docs/CHANGELOG.md
  src/components/homepage/homepage.js
Labels: ready for qa

#8672 8617 - Fix missing frozen columns
  .vscode/spellright.dict
  app/app.js
  app/src/js/middleware/option-handler-fonts.js
  app/views/components/datagrid/example-splitter.html
  app/views/components/datagrid/test-frozen-only.html
  app/views/components/locale/test-translations.html
  app/views/includes/head.html
  app/www/fonts/source-sans-pro-cyrillic-300-v22.woff2
  app/www/fonts/source-sans-pro-cyrillic-400-v22.woff2
  app/www/fonts/source-sans-pro-cyrillic-600-v22.woff2
  app/www/fonts/source-sans-pro-cyrillic-ext-300-v22.woff2
  app/www/fonts/source-sans-pro-cyrillic-ext-400-v22.woff2
  app/www/fonts/source-sans-pro-cyrillic-ext-600-v22.woff2
  app/www/fonts/source-sans-pro-greek-300-v22.woff2
  app/www/fonts/source-sans-pro-greek-400-v22.woff2
  app/www/fonts/source-sans-pro-greek-600-v22.woff2
  app/www/fonts/source-sans-pro-greek-ext-300-v22.woff2
  app/www/fonts/source-sans-pro-greek-ext-400-v22.woff2
  app/www/fonts/source-sans-pro-greek-ext-600-v22.woff2
  app/www/fonts/source-sans-pro-latin-300-v22.woff2
  app/www/fonts/source-sans-pro-latin-400-v22.woff2
  app/www/fonts/source-sans-pro-latin-600-v22.woff2
  app/www/fonts/source-sans-pro-latin-ext-300-v22.woff2
  app/www/fonts/source-sans-pro-latin-ext-400-v22.woff2
  app/www/fonts/source-sans-pro-latin-ext-600-v22.woff2
  app/www/fonts/source-sans-pro-v14-vietnamese_latin_greek-600.woff
  app/www/fonts/source-sans-pro-v14-vietnamese_latin_greek-600.woff2
  app/www/fonts/source-sans-pro-v14-vietnamese_latin_greek-regular.woff
  app/www/fonts/source-sans-pro-v14-vietnamese_latin_greek-regular.woff2
  app/www/fonts/source-sans-pro-vietnamese-300-v22.woff2
  app/www/fonts/source-sans-pro-vietnamese-400-v22.woff2
  app/www/fonts/source-sans-pro-vietnamese-600-v22.woff2
  docs/CHANGELOG.md
  src/components/datagrid/_datagrid.scss
  src/components/datagrid/datagrid.js
  src/components/typography/_typography-new.scss
  src/components/typography/font-face-snap-shot.txt
  src/components/typography/readme.md
  src/index.js
  src/utils/font-face.js
Labels: ready for qa

#8634 8600 - Added background settings for homepage and hero widget
  app/views/components/homepage/example-background-image.html
  app/www/images/background-image.svg
  app/www/images/banner-icon.png
  docs/CHANGELOG.md
  src/components/circlepager/circlepager.js
  src/components/homepage/_homepage.scss
  src/components/homepage/homepage.js
  src/components/homepage/readme.md
  src/components/pie/pie.js
Labels: priority: high

#8681 8626 - Lookup Min Width
  docs/CHANGELOG.md
  src/components/lookup/lookup.js
Labels: team: CSD

#8694 Misc - Fix beta bugs around buttons
  app/views/components/cards/example-workspace-widgets.html
  app/views/components/timepicker/test-states.html
  src/components/button/_button-new.scss
  src/components/button/_button.scss
  src/components/calendar/_calendar.scss
  src/components/cards/_cards.scss
  src/components/contextualactionpanel/_contextualactionpanel.scss
  src/components/datepicker/_datepicker.scss
  src/components/input/_input-new.scss
  src/components/masthead/_masthead-new.scss
  src/components/masthead/_masthead.scss
  src/components/popupmenu/popupmenu.js
  src/components/timepicker/_timepicker.scss
  src/core/_config.scss
  src/themes/theme-classic-contrast.scss
  src/themes/theme-classic-dark.scss
  src/themes/theme-classic-light.scss
  src/themes/theme-new-contrast.scss
  src/themes/theme-new-dark.scss
  src/themes/theme-new-light.scss
Labels: type: patch, priority: high

#8698 8624 - Add Row Alternate
  app/views/components/datagrid/test-addrow-alternate.html
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.js
Labels: ready for qa

#8700 8618 - Autocomplete Keydown
  docs/CHANGELOG.md
  src/components/popupmenu/popupmenu.js
Labels: ready for qa

#8705 NG1675 - BarStacked/ColumnStacked Many Records
  app/views/components/bar-stacked/test-many-records.html
  app/views/components/column-stacked/test-many-records.html
  docs/CHANGELOG.md
  src/components/charts/charts.js
Labels: ready for qa

#8716 8502 - Remove mobile spec in about
  docs/CHANGELOG.md
  src/components/about/about.js
Labels: ready for qa

#8727 8723 - Added fix for menu button
  docs/CHANGELOG.md
  src/components/applicationmenu/_applicationmenu.scss
Labels: ready for qa

#8718 8709 - Added fix to guard for errors
  .nvmrc
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.js
Labels: ready for qa

#8725 NG1646 - fix tooltip not showing after selecting item in lookup
  app/views/components/lookup/test-beforeshow.html
  docs/CHANGELOG.md
  src/components/lookup/lookup.js
Labels: ready for qa

#8731 8715 - Add new dependencies and icons
  app/package.json
  docs/CHANGELOG.md
  package-lock.json
  package.json
Labels: ready for qa

#8732 8728 - Add fix for editing frozen columns and one column
  app/views/components/datagrid/test-frozen-cell-shift.html
  docs/CHANGELOG.md
  src/components/datagrid/_datagrid.scss
Labels: ready for qa

#8733 8659 - Fixed RTL alignments and border colors for field filter
  docs/CHANGELOG.md
  src/components/dropdown/_dropdown-new.scss
  src/components/dropdown/dropdown.js
  src/components/field-filter/_field-filter-new.scss
  src/components/field-filter/_field-filter.scss
Labels: ready for qa

#8726 8724 - Fix alert icon position in RTL
  app/views/components/listview/example-paging-clientside.html
  docs/CHANGELOG.md
  src/components/cards/_cards.scss
  src/components/listview/_listview-new.scss
  src/components/listview/_listview.scss
Labels: ready for qa

#8710 7892 - Add fileupload-advanced in a homepage widget and forms
  app/views/components/fileupload-advanced/example-in-a-homepage-widget.html
  app/views/components/fileupload-advanced/example-in-forms.html
  docs/CHANGELOG.md
  src/components/cards/_cards.scss
  src/components/form/_form-new.scss
  src/components/form/_form.scss
  src/components/grid/_grid.scss
  src/components/homepage/_homepage.scss
Labels: ready for qa

#8735 8719 - Datagrid Cell Changed Trigger
  app/views/components/datagrid/test-cell-changed.html
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.js
Labels: priority: high, ready for qa

#8738 8485. Adjusted width
  app/views/components/module-nav/test-six-columns.html
  docs/CHANGELOG.md
  src/components/grid/_grid.scss
Labels: ready for qa

#8741 8737 - Add fixes for big ints
  app/views/components/datagrid/test-format-number.html
  docs/CHANGELOG.md
  src/components/locale/locale.js
Labels: type: patch, priority: high, ready for qa

#8661 7826 - Calendar Custom Colors
  app/data/custom-event-colors.json
  app/data/custom-events.json
  app/views/components/calendar/test-event-custom-colors.html
  docs/CHANGELOG.md
  src/components/calendar/calendar-shared.js
  src/components/calendar/calendar.js
  src/components/monthview/_monthview.scss
  src/components/tooltip/_tooltip.scss
  src/components/tooltip/tooltip.js
  src/components/week-view/week-view.js
  test/components/calendar/calendar-puppeteer-test.js
Labels: type: enhancement :sparkles:, ready for qa

#8749 8745 - Datagrid Dropdown Filter Keys
  docs/CHANGELOG.md
  src/components/datagrid/_datagrid.scss
  src/components/dropdown/dropdown.js
Labels: type: patch, priority: high

#8743 8677 - Fix datagrid pager and data in `updateDataset` and `loadData`
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.js
  test/components/datagrid/datagrid-selection-func-test.js
Labels: ready for qa

#8765 8527. Fixed module nav refreshing selected in accordion when closing then opening
  docs/CHANGELOG.md
  src/components/accordion/accordion.js
  src/components/module-nav/module-nav.js
Labels: ready for qa

#8754 7909 - Add `truncated` setting with tootltip on validation messages
  app/views/components/validation/test-truncated-with-tooltip.html
  docs/CHANGELOG.md
  src/components/input/_input-new.scss
  src/components/input/_input.scss
  src/components/validation/readme.md
  src/components/validation/validator.js
Labels: ready for qa

#8764 NG1681 - Fix on updateVal
  app/views/components/spinbox/example-range-limits.html
  docs/CHANGELOG.md
  src/components/spinbox/spinbox.js
Labels: ready for qa
