Repository infor-design/enterprise, pull requests merged in 2024-07, with the labels that each got.

#8856 8016 - Reorder tags
  app/views/components/tabs-module/example-sortable.html
  docs/CHANGELOG.md
  src/components/tabs-header/_tabs-header-new.scss
  src/components/tabs-module/_tabs-module.scss
  src/components/tabs/tabs.js
  src/core/_config.scss
Labels: ready for qa

#8866 NG1651 - Fixed asterisk being cut off when textOverflow is set to ellipsis
  app/views/components/datagrid/example-editable.html
  app/views/components/datagrid/test-ellipsis.html
  docs/CHANGELOG.md
  src/components/datagrid/_datagrid.scss
Labels: ready for qa

#8873 8825 - Override Tabbing Datagrid
  app/views/components/datagrid/test-override-tabbing.html
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.js
  tests-to-convert/components/datagrid/datagrid-settings-func-test.js
Labels: priority: high, ready for qa

#8874 NG1665 - Event handler for appmenu to click tab
  app/views/components/tabs-module/example-index.html
  docs/CHANGELOG.md
  src/components/tabs/tabs.js
Labels: ready for qa

#8885 8812 - Badge Toolbar Mobile
  app/views/components/toolbar/test-notification-badge.html
  docs/CHANGELOG.md
  src/components/notification-badge/notification-badge.js
  src/components/toolbar/_toolbar.scss
  tests/notification-badge/snapshots/notification-badge-html.snap
Labels: ready for qa

#8898 8896 - Added fix for switch click event
  docs/CHANGELOG.md
  src/components/switch/_switch.scss
Labels: type: patch, ready for qa

#8891 8889 - Fix error on datagrid eror expanding rows
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.js
Labels: ready for qa

#8908 1731 - Cards Selected and Deselected Event
  app/views/components/cards/example-multi-select.html
  app/views/components/cards/example-single-select.html
  docs/CHANGELOG.md
  src/components/cards/cards.js
Labels: ready for qa

#8886 8846 - Tabs Vertical Tooltip
  app/views/components/tabs-vertical/example-index.html
  docs/CHANGELOG.md
  src/components/tabs-vertical/_tabs-vertical.scss
  src/components/tabs/tabs.js
Labels: ready for qa

#8922 Misc - Fix child selection and demo app example
  app/views/components/datagrid/example-disabled-selection-checkbox.html
  app/views/components/datagrid/example-index.html
  app/views/components/datagrid/example-tree-disabled-selection-checkbox.html
  docs/CHANGELOG.md
  src/components/datagrid/_datagrid-new.scss
  src/components/datagrid/datagrid.formatters.js
  src/components/datagrid/datagrid.js
  src/components/switch/_switch.scss
Labels: priority: high

#8933 Misc - Fix for 3 Release bugs
  app/views/components/button/example-menubutton-replace-text.html
  app/views/components/button/example-menubutton.html
  app/views/components/datagrid/example-index.html
  app/views/components/line/test-axis-y-format-hours.html
  docs/CHANGELOG.md
  src/components/button/_button.scss
  src/components/datepicker/_datepicker-new.scss
  src/components/datepicker/_datepicker.scss
  src/components/header/_header.scss
  src/components/input/_input.scss
  src/components/switch/_switch.scss
  src/core/_config.scss
  src/themes/theme-new-dark.scss
Labels: priority: high
