Repository infor-design/enterprise, pull requests merged in 2024-02, with the labels that each got.

#8407 Add fixes for masthead colors
  app/views/components/masthead/example-banner-detail.html
  app/views/components/masthead/test-different-button-types.html
  app/views/includes/masthead.html
  docs/CHANGELOG.md
  src/components/masthead/_masthead.scss
Labels: type: patch, needs qa

#8412 8405 - Fix tab layout issues in left and right to left
  app/views/components/tabs-header/example-add-tab-button.html
  docs/CHANGELOG.md
  src/components/tabs-header/_tabs-header-new.scss
  src/components/tabs-header/_tabs-header.scss
  src/components/tabs-vertical/_tabs-vertical-new.scss
  src/components/tabs-vertical/_tabs-vertical.scss
  src/components/tabs/_tabs-new.scss
  src/components/tabs/_tabs.scss
  src/components/tabs/tabs.js
  src/core/_config.scss
Labels: type: patch, needs qa

#8413 8408 - Datagrid Datepicker Focus
  docs/CHANGELOG.md
  src/components/datagrid/_datagrid-new.scss
  src/components/datagrid/_datagrid.scss
  src/components/datagrid/datagrid.js
  test/components/datagrid/datagrid-puppeteer-test.js
  test/components/datagrid/datagrid-puppeteer-visual-test.js
Labels: priority: high, needs qa

#8415 8372 - Add data automation id in grid tooltip
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.js
Labels: needs qa

#8423 8422 - Fix audible spans in masthead
  docs/CHANGELOG.md
  src/components/masthead/_masthead.scss
Labels: needs qa

#8429 NG1635 - Lookup Manual Input Selection
  app/views/components/lookup/test-lookup-source-async.html
  docs/CHANGELOG.md
  src/components/lookup/lookup.js
Labels: needs qa

#8424 8421 - Fix tags close button alignment
  docs/CHANGELOG.md
  src/components/badges/_badges-new.scss
  src/components/badges/_badges.scss
  src/components/button/_button-new.scss
  src/components/button/_button.scss
  src/components/dropdown/_dropdown-new.scss
  src/components/dropdown/_dropdown.scss
Labels: needs qa

#8426 7933 - Add legend title in donut and pie charts
  app/views/components/donut/example-legend-with-title.html
  app/views/components/pie/example-legend-with-title.html
  docs/CHANGELOG.md
  src/components/charts/_charts-new.scss
  src/components/charts/_charts.scss
  src/components/charts/charts.js
  src/components/donut/readme.md
  src/core/_config.scss
  src/themes/theme-classic-dark.scss
  src/themes/theme-new-dark.scss
Labels: needs qa

#8425 8285 - Fixed cell value replacing special characters on cell change
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.js
  test/components/datagrid/datagrid-puppeteer-test.js
Labels: type: patch, priority: high, needs qa

#8437 8397 - Fix slider ticks visibility inside of a modal
  docs/CHANGELOG.md
  src/themes/theme-new-dark.scss
Labels: needs qa

#8436 NG1616 - Selection Focus Tree Grid after Change/Blur
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.js
Labels: needs qa

#8435 8373 - Add `dateTimestamp` date format
  docs/CHANGELOG.md
  src/components/locale/cultures/af-ZA.js
  src/components/locale/cultures/ar-EG.js
  src/components/locale/cultures/ar-SA.js
  src/components/locale/cultures/bg-BG.js
  src/components/locale/cultures/cs-CZ.js
  src/components/locale/cultures/da-DK.js
  src/components/locale/cultures/de-DE.js
  src/components/locale/cultures/el-GR.js
  src/components/locale/cultures/en-AU.js
  src/components/locale/cultures/en-GB.js
  src/components/locale/cultures/en-IN.js
  src/components/locale/cultures/en-NZ.js
  src/components/locale/cultures/en-US.js
  src/components/locale/cultures/en-ZA.js
  src/components/locale/cultures/es-419.js
  src/components/locale/cultures/es-AR.js
  src/components/locale/cultures/es-ES.js
  src/components/locale/cultures/fr-CA.js
  src/components/locale/cultures/lt-LT.js
  src/components/locale/cultures/sv-SE.js
  src/components/locale/locale.js
Labels: needs qa

#8442 8434 - Header Tabs Max Width
  app/views/components/tabs-header/test-max-width.html
  docs/CHANGELOG.md
  src/components/tabs-header/_tabs-header-new.scss
  src/components/tabs/tabs.js
Labels: type: patch, priority: high

#8440 1620 - Fix popup selection bug
  docs/CHANGELOG.md
  src/components/charts/_charts.scss
  src/components/charts/charts.js
  src/components/pie/pie.js
  src/components/popupmenu/popupmenu.js
  src/components/tabs/tabs.js
  src/components/tooltip/_tooltip.scss
Labels: type: patch, priority: high, needs qa

#8377 copy deploy script
  scripts/publish-docs/Dockerfile
  scripts/publish-docs/run.sh
  scripts/publish-docs/scripts/publish-docs.js
Labels: status: wip :construction:

#8441 NG1614 - Tooltip Special Characters
  app/views/components/tooltip/test-tooltip-number-sign.html
  docs/CHANGELOG.md
  src/components/tooltip/tooltip.js
Labels: needs qa

#8447 Misc - Added an alternative fix for XSS vulnerability
  app/views/components/datagrid/example-editable-with-row-status.html
  src/components/datagrid/_datagrid.scss
  src/components/datagrid/datagrid.js
Labels: priority: critical, needs qa

#8454 8308 - RTL Checkbox Dirty
  docs/CHANGELOG.md
  src/components/checkboxes/_checkboxes.scss
Labels: needs qa

#8458 8344/8411 - Fix Subcomponents not closing when hitting the escape key
  app/views/components/modal/test-editable-colorpicker-on-modal.html
  app/views/components/modal/test-modal-field-filter.html
  docs/CHANGELOG.md
  src/components/modal/_modal-new.scss
  src/components/modal/modal.js
Labels: needs qa

#8461 8459 - Fix cell readonly background color in dark mode
  docs/CHANGELOG.md
  src/themes/theme-new-dark.scss
Labels: needs qa

#8463 8303 - Fix close icon lookup modal in RTL
  docs/CHANGELOG.md
  src/components/lookup/_lookup-new.scss
  src/components/lookup/_lookup.scss
Labels: needs qa

#8465 8307 - Fix spinbox value position in RTL mode
  docs/CHANGELOG.md
  src/components/spinbox/_spinbox.scss
Labels: needs qa

#8486 8479 - Fix date parsing issue
  app/views/components/datagrid/test-date-parsing.html
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.js
Labels: type: patch, needs qa

#8409 3870 - Added tree in calendar events
  app/views/components/calendar/test-calendar-event-tree.html
  docs/CHANGELOG.md
  src/components/calendar/_calendar.scss
  src/components/calendar/calendar-shared.js
  src/components/calendar/calendar.js
  src/components/tree/_tree.scss
  src/components/tree/tree.js
Labels: needs qa

#8451 8404 - Tabs Module Spillover Alabaster
  docs/CHANGELOG.md
  src/components/personalize/_personalize.scss
  src/components/personalize/personalize.js
  src/components/personalize/personalize.styles.js
  src/components/tabs-header/_tabs-header-new.scss
  src/components/tabs-module/_tabs-module-new.scss
  src/components/tabs-module/_tabs-module.scss
  src/components/tabs/_tabs.scss
  src/core/_config.scss
  src/themes/theme-new-contrast.scss
  src/themes/theme-new-dark.scss
  src/themes/theme-new-light.scss
Labels: needs qa

#8455 8305 - RTL Dropdown Select
  docs/CHANGELOG.md
  src/components/badges/_badges-new.scss
  src/components/badges/_badges.scss
  src/components/dropdown/_dropdown-new.scss
  src/components/place/place.js
Labels: needs qa

#8493 8472 - Fix text moves upward when focused
  docs/CHANGELOG.md
  src/components/datagrid/_datagrid.scss
Labels: needs qa

#8468 8112 - CAP Back Arrow
  app/views/components/contextualactionpanel/test-back-button.html
  docs/CHANGELOG.md
  src/components/cards/cards.js
  src/components/contextualactionpanel/_contextualactionpanel-new.scss
  src/components/contextualactionpanel/_contextualactionpanel.scss
  src/components/contextualactionpanel/contextualactionpanel.js
  src/components/toolbar/_toolbar.scss
Labels: needs qa

#8497 8457 - Datagrid Editable Left Right Transfer Cells
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.js
Labels: needs qa

#8478 8367 - Graph Many Records
  app/views/components/pie/test-many-records.html
  docs/CHANGELOG.md
  src/components/charts/charts.js
  src/components/pie/pie.js
Labels: needs qa

#8495 8488 - Tabs Vertical Undefined
  app/views/components/tabs-vertical/test-no-initial-vertical-tabs.html
  docs/CHANGELOG.md
  src/components/tabs/tabs.js
Labels: priority: high, needs qa

#8471 8306 - RTL Color Picker
  docs/CHANGELOG.md
  src/components/colorpicker/_colorpicker-new.scss
  src/components/colorpicker/_colorpicker.scss
  src/components/place/place.js
Labels: needs qa

#8494 7112 - Searchfield Non Collapsible Mobile View
  docs/CHANGELOG.md
  src/components/searchfield/_searchfield-toolbar.scss
  src/components/toolbar-flex/_toolbar-flex.scss
  src/core/_config.scss
Labels: needs qa
