Repository infor-design/enterprise, pull requests merged in 2024-01, with the labels that each got.

#8287 8147 - Datagrid Filter Range
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.js
Labels: needs qa

#8292 8216 - Fixed dropdown icon misalignment in extra small rowheight
  docs/CHANGELOG.md
  src/components/datagrid/_datagrid-new.scss
  src/components/datagrid/_datagrid.scss
  src/components/dropdown/_dropdown-new.scss
Labels: needs qa

#8299 8274 - Fixed size in close button of tab list
  docs/CHANGELOG.md
  src/components/tabs/_tabs.scss
Labels: needs qa

#8302 8018 - fix modal shifting up when toggling switch inside of it
  app/views/components/modal/example-with-switch.html
  docs/CHANGELOG.md
  src/components/switch/_switch.scss
Labels: needs qa

#8320 8265 - Tabs Header Contrast Classic
  docs/CHANGELOG.md
  src/components/personalize/personalize.styles.js
Labels: needs qa

#8314 8241 - Adjusted alignment of icon in compact process indicator
  docs/CHANGELOG.md
  src/components/processindicator/_processindicator-new.scss
  src/components/processindicator/_processindicator.scss
Labels: needs qa

#8316 8271 - Tabs Module More Button
  docs/CHANGELOG.md
  src/components/personalize/personalize.styles.js
Labels: needs qa

#8321 8313 - Change chinese locale
  docs/CHANGELOG.md
  package-lock.json
  src/components/locale/cultures/zh-CN.js
  src/components/locale/cultures/zh-Hans.js
  src/components/locale/cultures/zh-Hant.js
  src/components/locale/cultures/zh-TW.js
  test/components/locale/locale-func-test.js
  test/components/timepicker/timepicker-puppeteer-test.js
Labels: needs qa

#8323 8094 - add `showPager` and `hidePager` methods
  app/views/components/datagrid/test-show-and-hide-pager.html
  docs/CHANGELOG.md
  src/components/pager/pager.js
Labels: needs qa

#8325 8208 - Fixed alignments of searchfield icons in RTL
  docs/CHANGELOG.md
  src/components/toolbar/_toolbar-new.scss
  src/components/toolbar/_toolbar.scss
Labels: needs qa

#8326 8225 - Changed selected border color for link card
  docs/CHANGELOG.md
  src/components/link/_link.scss
  src/core/_config.scss
  src/themes/theme-classic-dark.scss
  src/themes/theme-new-dark.scss
Labels: needs qa

#8329 8327 - Added example with back button
  app/views/components/header/example-hamburger-back.html
  app/views/includes/header-appmenu-back.html
  docs/CHANGELOG.md
Labels: needs qa

#8322 Misc - Merge preview release with new icons and alabaster default
  app/data/icons.js
  app/package.json
  app/src/js/middleware/option-handler-themes.js
  app/src/js/routes/custom-icons.js
  app/views/components/datagrid/example-grouped-headers.html
  app/views/components/icons/example-logos.html
  app/views/components/personalize/example-form-landmark.html
  app/views/components/personalize/example-form-landmark2-horizontal.html
  app/views/components/personalize/example-form-landmark2.html
  app/views/components/personalize/example-form.html
  app/views/components/personalize/example-form2.html
  app/views/components/personalize/test-classes-short.html
  app/views/components/personalize/test-form-short.html
  app/views/components/personalize/test-form2-short.html
  docs/CHANGELOG.md
  package-lock.json
  package.json
  scripts/build/create-svg-html.js
  src/components/button/_button.scss
  src/components/colors/_colors.scss
  src/components/counts/_counts.scss
  src/components/datagrid/_datagrid.scss
  src/components/editor/_editor-new.scss
  src/components/header/_header-new.scss
  src/components/header/_header.scss
  src/components/hyperlinks/_hyperlinks.scss
  src/components/icons/readme.md
  src/components/modal/_modal-new.scss
  src/components/modal/_modal.scss
  src/components/personalize/_personalize.scss
  src/components/personalize/personalize.js
  src/components/personalize/personalize.styles.js
  src/components/tabs-header/_tabs-header-new.scss
  src/components/tabs-header/_tabs-header.scss
  src/components/tabs/_tabs.scss
  src/components/tabs/tabs.js
  src/components/theme/theme.js
  src/components/toast/_toast.scss
  src/components/toolbar/_toolbar-new.scss
  src/core/_config.scss
  src/themes/theme-classic-contrast.scss
  src/themes/theme-classic-dark.scss
  src/themes/theme-classic-light.scss
  src/themes/theme-new-contrast.scss
  src/themes/theme-new-dark.scss
  src/themes/theme-new-light.scss
  test/components/line/line-api.func-spec.js
Labels: priority: high, needs qa

#8331 8212 - Cards Title Widget Alignment
  docs/CHANGELOG.md
  src/components/cards/_cards-new.scss
Labels: needs qa

#8335 8093 - Change datagrid example editable toolbar to flex toolbar
  app/views/components/datagrid/example-editable.html
  docs/CHANGELOG.md
Labels: needs qa

#8336 Change reset for compatibility
  docs/CHANGELOG.md
  src/core/_reset.scss
Labels: needs qa

#8338 8223 - Updated hover color for header searchfield clear icon
  docs/CHANGELOG.md
  src/components/personalize/_personalize.scss
  src/components/searchfield/_searchfield-new.scss
  src/themes/theme-classic-dark.scss
Labels: needs qa

#8345 8125 - Fixed a bug where textarea field is bigger than other fields on screen widths less that 400px
  docs/CHANGELOG.md
  src/components/modal/_modal.scss
Labels: needs qa

#8317 8275 - Tab Add Tab Button
  docs/CHANGELOG.md
  src/components/tabs/_tabs-horizontal-new.scss
  src/components/tabs/_tabs-new.scss
  src/components/tabs/_tabs.scss
  src/components/tabs/tabs.js
Labels: needs qa

#8315 8272 - Adjusted icon alignment and color for searchfield in tabs
  app/views/components/tabs-module/example-category-searchfield.html
  docs/CHANGELOG.md
  src/components/searchfield/_searchfield-toolbar.scss
  src/components/searchfield/_searchfield.scss
  src/components/tabs-module/_tabs-module-new.scss
  src/components/tabs-module/_tabs-module.scss
  src/components/tabs/_tabs.scss
  src/components/toolbar/_toolbar-new.scss
  src/components/toolbar/_toolbar.scss
Labels: needs qa

#8350 8252 - Added option to disable tooltip in columns
  app/views/components/datagrid/test-disable-tooltip-column.html
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.js
Labels: needs qa

#8356 8352 - [Preview] Datagrid Contextual Toolbar Hide Function
  app/views/components/datagrid/test-contextual-toolbar-hide.html
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.js
Labels: priority: critical, needs qa

#8357 8351 - [Preview] Cards Widget Header
  docs/CHANGELOG.md
  src/components/cards/_cards-new.scss
Labels: priority: critical, needs qa

#8358 8353 - [Preview] Dropdown with Icon
  docs/CHANGELOG.md
  src/components/dropdown/dropdown.js
Labels: priority: critical, needs qa

#8369 8254 - Added setting to disable error icon in validation
  app/views/components/tabs-vertical/example-index.html
  docs/CHANGELOG.md
  src/components/validation/validator.js
Labels: needs qa

#8355 1609 - Fix popover and clean examples
  app/views/components/modal/test-external-components.html
  app/views/components/modal/test-popover.html
  app/views/components/popover/example-alternate-positions.html
  app/views/components/popover/example-extra-css-class.html
  app/views/components/popover/example-index.html
  app/views/components/popover/test-attached-to-textbox.html
  app/views/components/popover/test-content-string.html
  app/views/components/popover/test-header-color.html
  app/views/components/popover/test-immediate.html
  app/views/components/popover/test-inline-data-options.html
  app/views/components/popover/test-inline-options.html
  app/views/components/popover/test-popover-scrollable.html
  app/views/components/popover/test-popover-textarea.html
  app/views/components/popover/test-popover-tooltip-same-button.html
  app/views/components/popover/test-popover-tooltip.html
  app/views/components/popover/test-popover-with-nested-tooltip.html
  app/views/components/popover/test-using-max-width-setting.html
  app/views/components/tag/example-popover.html
  docs/CHANGELOG.md
  src/components/popover/readme.md
  src/components/tooltip/tooltip.js
  test/components/popover/popover-puppeteer-test.js
Labels: needs qa

#8347 8248 - Update Disabled Days and Legend
  app/views/components/calendar/test-disabled-on-render.html
  docs/CHANGELOG.md
  src/components/calendar/_calendar.scss
  src/components/calendar/calendar.js
  src/components/monthview/_monthview.scss
  src/components/monthview/monthview.js
Labels: type: enhancement :sparkles:, needs qa

#8348 8015 - Fixed focus border style
  docs/CHANGELOG.md
  src/components/checkboxes/_checkboxes.scss
  src/components/radios/_radios.scss
  src/core/_config.scss
Labels: needs qa

#8378 8206 - Added css setting for lookup
  app/views/components/lookup/test-custom-css.html
  docs/CHANGELOG.md
  src/components/lookup/lookup.js
Labels: needs qa

#8384 8374 - Add avatar classes for module nav
  app/views/components/images/example-avatar.html
  app/views/components/images/example-photos.html
  app/views/components/module-nav/example-hide-show-sections.html
  docs/CHANGELOG.md
  src/components/cards/_cards.scss
  src/components/images/_images.scss
  src/components/images/readme.md
  src/components/module-nav/module-nav.guest.scss
Labels: needs qa

#8330 NG1605 - Searchfield Category Compact
  app/views/components/searchfield/test-searchfield-category-compact.html
  docs/CHANGELOG.md
  src/components/button/_button-new.scss
  src/components/button/_button.scss
  src/components/searchfield/_searchfield-new.scss
  src/components/searchfield/searchfield.js
  src/core/_config.scss
Labels: needs qa

#8371 8198 - Datagrid Frozen Column Prevent Reorder
  app/views/components/datagrid/test-frozen-columns.html
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.js
Labels: needs qa

#8366 8362 - Adjust top and bottom padding on home pages
  docs/CHANGELOG.md
  src/components/homepage/_homepage.scss
  src/components/homepage/homepage.js
  src/components/tabs-vertical/_tabs-vertical.scss
  test/components/button/button-puppeteer-visual-test.js
Labels: needs qa

#8368 5065 - New Calendar Designs For Selected, Current, Focus and Hover
  app/views/components/calendar/example-index.html
  docs/CHANGELOG.md
  src/components/calendar/_calendar-toolbar-new.scss
  src/components/calendar/_calendar-toolbar.scss
  src/components/calendar/calendar.js
  src/components/monthview/_monthview.scss
  src/components/monthview/monthview.js
  src/components/week-view/_week-view.scss
  src/components/week-view/week-view.js
  src/core/_config.scss
  src/themes/theme-classic-contrast.scss
  src/themes/theme-classic-dark.scss
  src/themes/theme-new-contrast.scss
  src/themes/theme-new-dark.scss
  src/themes/theme-new-light.scss
Labels: type: enhancement :sparkles:, needs qa

#8370 8310/8311/8312 - Gen AI
  app/views/components/busyindicator/example-ai-loading-indicator.html
  app/views/components/button/example-index.html
  app/views/components/editor/example-with-backcolor.html
  app/views/components/editor/example-with-gen-ai-button.html
  app/views/includes/head.html
  docs/CHANGELOG.md
  scripts/data/expected-files.json
  src/components/busyindicator/_busyindicator.scss
  src/components/button/_button-new.scss
  src/components/button/_button.scss
  src/components/button/button.js
  src/components/button/readme.md
  src/components/editor/_editor.scss
  src/components/editor/editor.js
  src/components/locale/cultures/en-US.js
  src/components/tooltip/_tooltip.scss
  src/core/_config.scss
  src/themes/theme-new-dark.scss
Labels: needs qa

#8392 8391 - Fix incorrect color on hover
  docs/CHANGELOG.md
  src/components/masthead/_masthead-new.scss
  src/components/masthead/_masthead.scss
Labels: type: patch
