Repository infor-design/enterprise, pull requests merged in 2024-03, with the labels that each got.

#8500 8363 - Fixed increment/decrement and today key being activated in range mode
  app/views/components/datagrid/test-filter-date-hide-days.html
  docs/CHANGELOG.md
  src/components/datepicker/datepicker.js
Labels: needs qa

#8503 8427 - Added escape HTML in updateNode
  app/views/components/tree/test-escape-node.html
  docs/CHANGELOG.md
  src/components/tree/tree.js
Labels: needs qa

#8491 8334 - Fixed alignment issues in go button
  app/views/components/toolbarsearchfield/example-flex-toolbar-align-with-searchfield.html
  docs/CHANGELOG.md
  src/components/searchfield/_searchfield-toolbar.scss
  src/components/searchfield/searchfield.js
  src/components/toolbar-flex/_toolbar-flex-searchfield-new.scss
  src/components/toolbar-flex/_toolbar-flex-searchfield.scss
  src/components/toolbar-flex/_toolbar-flex.scss
Labels: needs qa

#8499 8293 - RTL Datagrid Small Row Height
  app/views/components/datagrid/example-editable.html
  docs/CHANGELOG.md
  src/components/datagrid/_datagrid-new.scss
  src/components/datagrid/_datagrid.scss
Labels: needs qa

#8507 NG1639 - Fixed a bug where parent modal closes instead of currently active modal when pressing the escape key
  app/views/components/modal/test-nested.html
  docs/CHANGELOG.md
  src/components/modal/modal.manager.js
Labels: needs qa

#8517 8452 - Calendar Turqoise
  app/views/components/calendar/test-all-colors.html
  docs/CHANGELOG.md
  src/components/calendar/calendar-shared.js
Labels: needs qa

#8519 8193 - Fixed alignment in short form of radio button
  docs/CHANGELOG.md
  src/components/radios/_radios.scss
Labels: needs qa

#8512 8399 - Fixed alignment issues in clear button
  docs/CHANGELOG.md
  src/components/button/_button-new.scss
  src/components/button/_button.scss
  src/components/searchfield/_searchfield-new.scss
  src/components/searchfield/_searchfield.scss
Labels: needs qa

#8522 8211 - Added row height style classes for widgets
  app/views/components/homepage/example-height.html
  docs/CHANGELOG.md
  src/components/homepage/_homepage.scss
  src/components/homepage/homepage.js
Labels: needs qa

#8520 8516 - Removed escaping HTML for cell nodes
  app/views/components/datagrid/example-editable.html
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.js
Labels: needs qa

#8531 8417 - Datagrid Singleline Resize Handle
  app/views/components/datagrid/test-resize-handle-singleline.html
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.js
Labels: needs qa

#8535 8449 - Fix character count message
  docs/CHANGELOG.md
  src/components/locale/cultures/en-US.js
  src/components/textarea/textarea.js
  test/components/textarea/textarea-settings-func-test.js
Labels: needs qa

#8540 8539 - Make avatar not round
  app/views/components/images/example-avatar.html
  app/views/components/module-nav/example-icon.html
  app/views/components/module-nav/example-set-role-from-data.html
  docs/CHANGELOG.md
  src/components/images/_images.scss
Labels: type: patch, needs qa

#8528 7019 - Modal Draggable
  app/views/components/modal/test-draggable.html
  docs/CHANGELOG.md
  src/components/drag/drag.js
  src/components/modal/_modal.scss
  src/components/modal/modal.js
Labels: type: enhancement :sparkles:, needs qa

#8534 8431 - Fix axis labels visibility
  docs/CHANGELOG.md
  src/components/charts/_charts.scss
Labels: needs qa

#8545 8333 - Fixed cut-off searchfield button
  docs/CHANGELOG.md
  src/components/searchfield/_searchfield-toolbar-new.scss
  src/components/searchfield/_searchfield-toolbar.scss
  src/components/toolbar/_toolbar-new.scss
  src/components/toolbar/toolbar.js
Labels: needs qa

#8518 8439 - Datagrid Always on Icons
  app/views/components/datagrid/test-icon-always-on.html
  docs/CHANGELOG.md
  src/components/datagrid/_datagrid-new.scss
  src/components/datagrid/_datagrid.scss
  src/components/datagrid/datagrid.js
  src/components/place/place.js
  src/core/_config.scss
  src/themes/theme-new-light.scss
  test/components/datagrid/datagrid-settings-func-test.js
Labels: type: enhancement :sparkles:, needs qa

#8542 NG1570 - Disabled filter dropdown if selection is only one
  docs/CHANGELOG.md
  src/components/datagrid/_datagrid.scss
  src/components/datagrid/datagrid.js
Labels: needs qa

#8543 8433 - Datepicker Action Args
  app/views/components/calendar/example-index.html
  docs/CHANGELOG.md
  src/components/monthview/monthview.js
Labels: needs qa

#8552 NG1578 - Tabs Vetoable
  app/views/components/tabs/example-activated-event.html
  docs/CHANGELOG.md
  src/components/tabs/tabs.js
Labels: needs qa

#8533 8349 - Fixed alignment in datagrid radio button
  docs/CHANGELOG.md
  src/components/datagrid/_datagrid-new.scss
  src/components/datagrid/_datagrid.scss
Labels: needs qa

#8554 8416 - Added placeholder setting in toolbar
  app/views/components/lookup/example-filter-lookup.html
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.js
  src/components/searchfield/searchfield.js
  src/components/toolbar/toolbar.js
Labels: needs qa

#8544 NG1478 - Homepage Component Resize
  app/views/components/homepage/test-pager.html
  docs/CHANGELOG.md
  src/components/homepage/_homepage.scss
  src/components/homepage/homepage.js
Labels: needs qa

#8565 8448 - Fixed misalignment in card header icon
  docs/CHANGELOG.md
  src/components/cards/_cards-new.scss
  src/components/cards/_cards.scss
  src/components/cards/cards.js
Labels: needs qa

#8569 8460 - Fix 6th level accordion header position (Module Nav)
  docs/CHANGELOG.md
  src/components/module-nav/module-nav.accordion.scss
Labels: needs qa

#8568 8541 - GenAiButton Start Stop
  app/views/components/button/example-index.html
  app/views/components/button/test-generative-start-stop.html
  docs/CHANGELOG.md
  src/components/button/button.js
Labels: needs qa
