Repository infor-design/enterprise, pull requests merged in 2024-04, with the labels that each got.

#8576 8342 - Fixed clear button misalignment in RTL
  app/views/components/toolbar-flex/example-searchfield-collapsible.html
  docs/CHANGELOG.md
  src/components/toolbar-flex/_toolbar-flex-searchfield-new.scss
Labels: needs qa

#8563 8524 - Timeline Alignment
  app/views/components/cards/example-workspace-widgets.html
  app/views/components/timeline/test-on-widget.html
  docs/CHANGELOG.md
  src/components/timeline/_timeline.scss
Labels: needs qa

#8572 8430 - Toolbar Flex More Button
  app/views/components/datagrid/test-flex-toolbar.html
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.js
  src/components/toolbar-flex/_toolbar-flex.scss
  test/components/area/area-puppeteer-test.js
  test/components/locale/locale-func-test.js
  test/components/popdown/popdown-puppeteer-test.js
  test/components/popupmenu/popupmenu-puppeteer-test.js
  test/components/timepicker/timepicker-settings-func-test.js
Labels: needs qa

#8571 8410 - Charts Resize
  app/views/components/homepage/test-all-charts.html
  docs/CHANGELOG.md
  src/components/column/column.js
  src/components/homepage/homepage.js
  src/components/pie/pie.js
Labels: ready for qa

#8573 8446 - Tooltip Tabs Header
  app/views/components/tabs-header/test-max-width.html
  docs/CHANGELOG.md
  src/components/tabs/tabs.js
Labels: ready for qa

#8570 8504 - Fixed searchfield icon alignment in filter
  docs/CHANGELOG.md
  src/components/datagrid/_datagrid-new.scss
  src/components/datagrid/_datagrid.scss
  src/components/lookup/_lookup.scss
Labels: ready for qa

#8578 8498 - Select event is not triggered when clicking a hyperlink
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.js
Labels: ready for qa

#8577 8381 - Added setting to disable nav switcher
  app/views/components/module-nav/example-index.html
  docs/CHANGELOG.md
  src/components/module-nav/module-nav.dropdown.scss
  src/components/module-nav/module-nav.js
  src/components/module-nav/module-nav.switcher.js
Labels: ready for qa, needs design review

#8589 8438 - Added copy to clipboard button to about page
  docs/CHANGELOG.md
  src/components/about/_about.scss
  src/components/about/about.js
  src/components/locale/cultures/en-US.js
  src/utils/utils.js
Labels: type: patch, ready for qa, needs design review

#8588 8584 - Fix avatar shape on hierarchy
  docs/CHANGELOG.md
  src/components/hierarchy/_hierarchy-base.scss
Labels: type: patch, ready for qa

#8607 8462 - Fix on error popping up on dragging
  src/components/arrange/arrange.js
  src/components/drag/_drag.scss
Labels: ready for qa

#8603 8602 - Fix button layout regression
  docs/CHANGELOG.md
  src/components/cards/_cards-new.scss
  src/components/cards/_cards.scss
Labels: type: patch, ready for qa

#8581 8515 - Fixed search icon misalignment in dropdown cells
  docs/CHANGELOG.md
  src/components/datagrid/_datagrid-new.scss
  src/components/datagrid/_datagrid.scss
  src/components/dropdown/_dropdown-new.scss
Labels: ready for qa

#8604 8596 - Fix tab errors
  docs/CHANGELOG.md
  src/components/tabs/tabs.js
Labels: type: patch, ready for qa

#8609 fixes to the enterprise release pipeline
  scripts/publish-docs/Makefile
  scripts/publish-docs/job.yaml
  scripts/release/Dockerfile
  scripts/release/Makefile
  scripts/release/job.yaml
Labels: status: wip :construction:

#8614 Chore - Add new translations
  docs/CHANGELOG.md
  src/components/locale/cultures/ar-EG.js
  src/components/locale/cultures/bg-BG.js
  src/components/locale/cultures/cs-CZ.js
  src/components/locale/cultures/da-DK.js
  src/components/locale/cultures/de-DE.js
  src/components/locale/cultures/es-ES.js
  src/components/locale/cultures/et-EE.js
  src/components/locale/cultures/fi-FI.js
  src/components/locale/cultures/fr-CA.js
  src/components/locale/cultures/fr-FR.js
  src/components/locale/cultures/he-IL.js
  src/components/locale/cultures/hr-HR.js
  src/components/locale/cultures/hu-HU.js
  src/components/locale/cultures/id-ID.js
  src/components/locale/cultures/it-IT.js
  src/components/locale/cultures/ja-JP.js
  src/components/locale/cultures/ko-KR.js
  src/components/locale/cultures/lt-LT.js
  src/components/locale/cultures/lv-LV.js
  src/components/locale/cultures/ms-bn.js
  src/components/locale/cultures/ms-my.js
  src/components/locale/cultures/nn-NO.js
  src/components/locale/cultures/no-NO.js
  src/components/locale/cultures/zh-CN.js
  src/components/locale/cultures/zh-Hans.js
  test/components/locale/locale-func-test.js
Labels: ready for qa

#8612 8611 - Add fix for error with no widgets
  docs/CHANGELOG.md
  src/components/homepage/homepage.js
Labels: type: patch, priority: high, ready for qa

#8592 8332 - Fixed misalignment in clear icon on mobile
  docs/CHANGELOG.md
  src/components/toolbar-flex/_toolbar-flex-searchfield.scss
Labels: ready for qa

#8615 7315 - Updated month cursor
  docs/CHANGELOG.md
  src/components/monthview/_monthview.scss
Labels: ready for qa

#8613 8510 - Add timeline fixes
  app/views/components/timeline/test-additional-height.html
  app/views/components/timeline/test-on-card.html
  docs/CHANGELOG.md
  src/components/timeline/_timeline-new.scss
  src/components/timeline/_timeline.scss
Labels: type: patch, priority: high, ready for qa

#8595 8457 - Datagrid Editable Left Right Keys
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.js
Labels: ready for qa

#8628 8627 - Fixed error parsing some dates
  .github/workflows/ci.yml
  docs/CHANGELOG.md
  src/components/datagrid/_datagrid.scss
  src/components/datagrid/datagrid.js
Labels: ready for qa

#8622 2178 - Add support for ids-breadcrumb
  app/views/components/header/example-wc-breadcrumb.html
  app/views/components/header/test-no-personalize.html
  app/views/includes/head.html
  docs/CHANGELOG.md
  src/components/header/_header.scss
  src/components/personalize/personalize.js
  src/components/personalize/personalize.styles.js
  src/core/_config.scss
  src/themes/theme-classic-contrast.scss
  src/themes/theme-classic-dark.scss
  src/themes/theme-new-contrast.scss
  src/themes/theme-new-dark.scss
Labels: ready for qa

#8642 Chore: Try to fix builds build changing sass to node-sass
  .github/workflows/ci.yml
  .github/workflows/env-deploy.yml
  app/package.json
  package-lock.json
  package.json
  scripts/build/sass.js
  src/components/completion-chart/_completion-chart.scss
  src/components/editor/_editor.scss
  src/components/images/_images.scss
  src/components/input/_input.scss
  src/components/monthview/_monthview.scss
  src/components/processindicator/_processindicator.scss
  src/components/switch/_switch.scss
  src/components/timepicker/_timepicker.scss
  src/components/typography/_typography.scss
  src/components/wizard/_wizard.scss
  src/core/_mixins.scss
Labels: priority: high, ready for qa

#8648 8647 - Fix wrong Norwegian text
  docs/CHANGELOG.md
  src/components/locale/cultures/nb-NO.js
  src/components/locale/cultures/nl-NL.js
  src/components/locale/cultures/nn-NO.js
  src/components/locale/cultures/no-NO.js
Labels: ready for qa
