Repository infor-design/enterprise, pull requests merged in 2024-06, with the labels that each got.

#8771 8453 - Calendar Event Tooltips
  app/data/custom-events.json
  app/data/events.json
  app/views/components/calendar/test-event-tooltips.html
  docs/CHANGELOG.md
  src/components/calendar/calendar.js
  src/components/tooltip/tooltip.js
  src/components/week-view/week-view.js
  test/components/button/button-puppeteer-test.js
Labels: type: enhancement :sparkles:, team: WFM, ready for qa

#8753 8243 - Calendar Slide Select
  app/views/components/calendar/test-slide-select.html
  docs/CHANGELOG.md
  src/components/calendar/calendar.js
  src/components/monthview/_monthview.scss
  src/components/monthview/monthview.js
Labels: type: enhancement :sparkles:, team: landmark

#8813 Misc - Fix bug in RTL dropdown
  docs/CHANGELOG.md
  src/components/colorpicker/_colorpicker.scss
  src/components/dropdown/_dropdown-new.scss
  src/components/dropdown/dropdown.js
  src/components/fileupload/_fileupload.scss
Labels: ready for qa

#8816 8773 - Add fix to refresh tooltip
  app/views/components/datagrid/test-filter-with-default-operator.html
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.js
  src/components/tooltip/tooltip.js
Labels: ready for qa

#8781 8755 - Fixed bug where chart is cut off on bottom legend placement mode
  app/views/components/donut/test-legend-bottom.html
  docs/CHANGELOG.md
  src/components/charts/_charts.scss
  src/components/charts/charts.js
  src/components/pie/_pie.scss
  src/components/pie/pie.js
Labels: ready for qa

#8818 8768 - Dropdown No Results
  docs/CHANGELOG.md
  src/components/dropdown/dropdown.js
Labels: ready for qa

#8830 NG#1671 - Fix `charts.setSelected` method to work with different charts in a single page
  docs/CHANGELOG.md
  src/components/bar/bar.js
  src/components/charts/charts.js
  src/components/line/line.js
  test/components/bubble/bubble-api-func-test.js
Labels: ready for qa

#8829 8828 - Refix grid issue
  docs/CHANGELOG.md
  src/components/grid/_grid.scss
Labels: ready for qa

#8845 8618 - Autocomplete Keydown
  docs/CHANGELOG.md
  src/components/autocomplete/autocomplete.js
  src/components/popupmenu/popupmenu.js
Labels: ready for qa

#8851 8758 - Datagrid Focus With Button (Lookup)
  app/views/components/datagrid/test-grid-input-lost-focus.html
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.js
Labels: ready for qa

#8848 8817 - Fixed zindex on module nav
  docs/CHANGELOG.md
Labels: ready for qa

#8844 NG1700 - Fixed bug in popupmenu when heading element is added in NG
  docs/CHANGELOG.md
  src/components/popupmenu/popupmenu.js
  src/components/toolbar-flex/toolbar-flex.item.js
Labels: ready for qa

#8838 Fix incorrect updates in commitCellEditUtil
  app/views/components/datagrid/test-editable-inline-editor-quick-focus-change.html
  docs/CHANGELOG.md
  src/components/datagrid/datagrid.js
Labels: ready for qa

#8859 8773 - Add fix for new case on missing tooltip
  app/views/components/datagrid/test-filter-with-default-operator.html
  src/components/datagrid/datagrid.js
Labels: type: patch

#8833 8832 - Fix memory leak in datagrid
  src/components/datagrid/datagrid.editors.js
  src/components/datagrid/datagrid.js
Labels: ready for qa
